export const atoms = [
  {
    name: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    protons: 1,
    neutrons: 0,
    electrons: 1,
    color: 0xff0000,
    electronColor: 0x00ffff,
    xpos: 1,
    ypos: 1,
    reactivity: "Explosive",
    isReactive: true,
    description: "Hydrogen is a chemical element with symbol H and atomic number 1. It is classified as a Explosive.",
    melting: -259.14,
    boiling: -252.87,
    density: 8.988e-05,
    yearDiscovered: 1766,
    uses: "Fuel cells, ammonia production, rocket fuel",
    isotopes: [
      { mass: 1, neutrons: 0, name: "Protium", abundance: "99.98%", stable: true },
      { mass: 2, neutrons: 1, name: "Deuterium", abundance: "0.02%", stable: true },
      { mass: 3, neutrons: 2, name: "Tritium", abundance: "trace", stable: false }
    ]
  },
  {
    name: "Helium",
    symbol: "He",
    atomicNumber: 2,
    protons: 2,
    neutrons: 2,
    electrons: 2,
    color: 0x00ff4a,
    electronColor: 0xff00b4,
    xpos: 18,
    ypos: 1,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Helium is a chemical element with symbol He and atomic number 2. It is classified as a Noble Gas (Inert).",
    melting: null,
    boiling: -268.93,
    density: 0.0001785,
    yearDiscovered: 1868,
    uses: "Balloons, cryogenics, breathing mixtures",
    isotopes: [
      { mass: 3, neutrons: 1, name: "Helium-3", abundance: "0.000137%", stable: true },
      { mass: 4, neutrons: 2, name: "Helium-4", abundance: "99.999863%", stable: true }
    ]
  },
  {
    name: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    protons: 3,
    neutrons: 3,
    electrons: 3,
    color: 0x9400ff,
    electronColor: 0x6aff00,
    xpos: 1,
    ypos: 2,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Lithium is a chemical element with symbol Li and atomic number 3. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 180.5,
    boiling: 1342,
    density: 0.534,
    yearDiscovered: 1817,
    uses: "Batteries, ceramics, lubricants",
    isotopes: [
      { mass: 6, neutrons: 3, name: "Lithium-6", abundance: "7.5%", stable: true },
      { mass: 7, neutrons: 4, name: "Lithium-7", abundance: "92.5%", stable: true }
    ]

  },
  {
    name: "Beryllium",
    symbol: "Be",
    atomicNumber: 4,
    protons: 4,
    neutrons: 4,
    electrons: 4,
    color: 0xffdf00,
    electronColor: 0x001fff,
    xpos: 2,
    ypos: 2,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Beryllium is a chemical element with symbol Be and atomic number 4. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 1287,
    boiling: 2470,
    density: 1.85,
    yearDiscovered: 1798,
    uses: "Aerospace alloys, X-ray windows",
    isotopes: [
      { mass: 9, neutrons: 5, name: "Beryllium-9", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Boron",
    symbol: "B",
    atomicNumber: 5,
    protons: 5,
    neutrons: 5,
    electrons: 5,
    color: 0x00d4ff,
    electronColor: 0xff2a00,
    xpos: 13,
    ypos: 2,
    reactivity: "Moderate",
    isReactive: false,
    description: "Boron is a chemical element with symbol B and atomic number 5. It is classified as a Moderate.",
    melting: 2075,
    boiling: 4000,
    density: 2.34,
    yearDiscovered: 1808,
    uses: "Glass, detergents, semiconductors",
    isotopes: [
      { mass: 10, neutrons: 5, name: "Boron-10", abundance: "19.9%", stable: true },
      { mass: 11, neutrons: 6, name: "Boron-11", abundance: "80.1%", stable: true },
    ],
  },
  {
    name: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    protons: 6,
    neutrons: 6,
    electrons: 6,
    color: 0xff008a,
    electronColor: 0x00ff74,
    xpos: 14,
    ypos: 2,
    reactivity: "Moderate",
    isReactive: false,
    description: "Carbon is a chemical element with symbol C and atomic number 6. It is classified as a Moderate.",
    melting: 3550,
    boiling: 4027,
    density: 2.267,
    yearDiscovered: -3750,
    uses: "Steel, plastics, diamonds, graphite",
    isotopes: [
      { mass: 12, neutrons: 6, abundance: "98.9%", stable: true },
      { mass: 13, neutrons: 7, abundance: "1.1%", stable: true },
      { mass: 14, neutrons: 8, abundance: "trace", stable: false }
    ]
  },
  {
    name: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    protons: 7,
    neutrons: 7,
    electrons: 7,
    color: 0x3fff00,
    electronColor: 0xbf00ff,
    xpos: 15,
    ypos: 2,
    reactivity: "Moderate",
    isReactive: false,
    description: "Nitrogen is a chemical element with symbol N and atomic number 7. It is classified as a Moderate.",
    melting: -210,
    boiling: -195.79,
    density: 0.0012506,
    yearDiscovered: 1772,
    uses: "Fertilizers, explosives, food preservation",
    isotopes: [
      { mass: 14, neutrons: 7, name: "Nitrogen-14", abundance: "99.63%", stable: true },
      { mass: 15, neutrons: 8, name: "Nitrogen-15", abundance: "0.37%", stable: true },
    ],
  },
  {
    name: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    protons: 8,
    neutrons: 8,
    electrons: 8,
    color: 0x0a00ff,
    electronColor: 0xf4ff00,
    xpos: 16,
    ypos: 2,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Oxygen is a chemical element with symbol O and atomic number 8. It is classified as a Chalcogen (Reactive).",
    melting: -218.79,
    boiling: -182.95,
    density: 0.001429,
    yearDiscovered: 1774,
    uses: "Respiration, steel production, water treatment",
    isotopes: [
      { mass: 16, neutrons: 8, name: "Oxygen-16", abundance: "99.762%", stable: true },
      { mass: 17, neutrons: 9, name: "Oxygen-17", abundance: "0.038%", stable: true },
      { mass: 18, neutrons: 10, name: "Oxygen-18", abundance: "0.200%", stable: true },
    ],
  },
  {
    name: "Fluorine",
    symbol: "F",
    atomicNumber: 9,
    protons: 9,
    neutrons: 9,
    electrons: 9,
    color: 0xff5400,
    electronColor: 0x00a9ff,
    xpos: 17,
    ypos: 2,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Fluorine is a chemical element with symbol F and atomic number 9. It is classified as a Halogen (Highly Reactive).",
    melting: -219.62,
    boiling: -188.12,
    density: 0.001696,
    yearDiscovered: 1886,
    uses: "Toothpaste, refrigerants, Teflon",
    isotopes: [
      { mass: 19, neutrons: 10, name: "Fluorine-19", abundance: "100%", stable: true }
    ],
  },
  {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    protons: 10,
    neutrons: 10,
    electrons: 10,
    color: 0x00ff9f,
    electronColor: 0xff005f,
    xpos: 18,
    ypos: 2,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Neon is a chemical element with symbol Ne and atomic number 10. It is classified as a Noble Gas (Inert).",
    melting: -248.59,
    boiling: -246.08,
    density: 0.0008999,
    yearDiscovered: 1898,
    uses: "Neon signs, lasers, cryogenic refrigerant",
    isotopes: [
      { mass: 20, neutrons: 10, name: "Neon-20", abundance: "90.48%", stable: true },
      { mass: 21, neutrons: 11, name: "Neon-21", abundance: "0.27%", stable: true },
      { mass: 22, neutrons: 12, name: "Neon-22", abundance: "9.25%", stable: true },
    ],
  },
  {
    name: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    protons: 11,
    neutrons: 11,
    electrons: 11,
    color: 0xe900ff,
    electronColor: 0x15ff00,
    xpos: 1,
    ypos: 3,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Sodium is a chemical element with symbol Na and atomic number 11. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 97.72,
    boiling: 883,
    density: 0.971,
    yearDiscovered: 1807,
    uses: "Table salt, soap, street lights",
    isotopes: [
      { mass: 23, neutrons: 12, name: "Sodium-23", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    protons: 12,
    neutrons: 12,
    electrons: 12,
    color: 0xc9ff00,
    electronColor: 0x3500ff,
    xpos: 2,
    ypos: 3,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 650,
    boiling: 1090,
    density: 1.738,
    yearDiscovered: 1755,
    uses: "Alloys, fireworks, flash photography",
    isotopes: [
      { mass: 24, neutrons: 12, name: "Magnesium-24", abundance: "78.99%", stable: true },
      { mass: 25, neutrons: 13, name: "Magnesium-25", abundance: "10.00%", stable: true },
      { mass: 26, neutrons: 14, name: "Magnesium-26", abundance: "11.01%", stable: true },
    ],
  },
  {
    name: "Aluminum",
    symbol: "Al",
    atomicNumber: 13,
    protons: 13,
    neutrons: 13,
    electrons: 13,
    color: 0x007fff,
    electronColor: 0xff7f00,
    xpos: 13,
    ypos: 3,
    reactivity: "Moderate",
    isReactive: false,
    description: "Aluminum is a chemical element with symbol Al and atomic number 13. It is classified as a Moderate.",
    melting: 660.32,
    boiling: 2519,
    density: 2.698,
    yearDiscovered: 1825,
    uses: "Cans, foil, aircraft, construction",
    isotopes: [
      { mass: 27, neutrons: 14, name: "Aluminum-27", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Silicon",
    symbol: "Si",
    atomicNumber: 14,
    protons: 14,
    neutrons: 14,
    electrons: 14,
    color: 0xff0035,
    electronColor: 0x00ffc9,
    xpos: 14,
    ypos: 3,
    reactivity: "Moderate",
    isReactive: false,
    description: "Silicon is a chemical element with symbol Si and atomic number 14. It is classified as a Moderate.",
    melting: 1414,
    boiling: 3265,
    density: 2.3296,
    yearDiscovered: 1824,
    uses: "Computer chips, solar cells, glass",
    isotopes: [
      { mass: 28, neutrons: 14, name: "Silicon-28", abundance: "92.2%", stable: true },
      { mass: 29, neutrons: 15, name: "Silicon-29", abundance: "4.7%", stable: true },
      { mass: 30, neutrons: 16, name: "Silicon-30", abundance: "3.1%", stable: true },
    ],
  },
  {
    name: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    protons: 15,
    neutrons: 15,
    electrons: 15,
    color: 0x00ff15,
    electronColor: 0xff00e9,
    xpos: 15,
    ypos: 3,
    reactivity: "Moderate",
    isReactive: false,
    description: "Phosphorus is a chemical element with symbol P and atomic number 15. It is classified as a Moderate.",
    melting: 44.15,
    boiling: 280.5,
    density: 1.82,
    yearDiscovered: 1669,
    uses: "Fertilizers, detergents, matches",
    isotopes: [
      { mass: 31, neutrons: 16, name: "Phosphorus-31", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    protons: 16,
    neutrons: 16,
    electrons: 16,
    color: 0x5f00ff,
    electronColor: 0x9fff00,
    xpos: 16,
    ypos: 3,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Sulfur is a chemical element with symbol S and atomic number 16. It is classified as a Chalcogen (Reactive).",
    melting: 115.21,
    boiling: 444.6,
    density: 2.067,
    yearDiscovered: -2000,
    uses: "Sulfuric acid, gunpowder, vulcanizing rubber",
    isotopes: [
      { mass: 32, neutrons: 16, name: "Sulfur-32", abundance: "94.99%", stable: true },
      { mass: 33, neutrons: 17, name: "Sulfur-33", abundance: "0.75%", stable: true },
      { mass: 34, neutrons: 18, name: "Sulfur-34", abundance: "4.25%", stable: true },
      { mass: 36, neutrons: 20, name: "Sulfur-36", abundance: "0.01%", stable: true },
    ],
  },
  {
    name: "Chlorine",
    symbol: "Cl",
    atomicNumber: 17,
    protons: 17,
    neutrons: 17,
    electrons: 17,
    color: 0xffaa00,
    electronColor: 0x0054ff,
    xpos: 17,
    ypos: 3,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Chlorine is a chemical element with symbol Cl and atomic number 17. It is classified as a Halogen (Highly Reactive).",
    melting: -101.5,
    boiling: -34.04,
    density: 0.003214,
    yearDiscovered: 1774,
    uses: "Water purification, bleach, PVC",
    isotopes: [
      { mass: 35, neutrons: 18, name: "Chlorine-35", abundance: "75.76%", stable: true },
      { mass: 37, neutrons: 20, name: "Chlorine-37", abundance: "24.24%", stable: true },
    ],
  },
  {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    protons: 18,
    neutrons: 18,
    electrons: 18,
    color: 0x00fff4,
    electronColor: 0xff000a,
    xpos: 18,
    ypos: 3,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Argon is a chemical element with symbol Ar and atomic number 18. It is classified as a Noble Gas (Inert).",
    melting: -189.35,
    boiling: -185.85,
    density: 0.0017837,
    yearDiscovered: 1894,
    uses: "Welding, light bulbs, insulation",
    isotopes: [
      { mass: 36, neutrons: 18, name: "Argon-36", abundance: "0.334%", stable: true },
      { mass: 38, neutrons: 20, name: "Argon-38", abundance: "0.063%", stable: true },
      { mass: 40, neutrons: 22, name: "Argon-40", abundance: "99.604%", stable: true },
    ],
  },
  {
    name: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    protons: 19,
    neutrons: 19,
    electrons: 19,
    color: 0xff00bf,
    electronColor: 0x00ff3f,
    xpos: 1,
    ypos: 4,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Potassium is a chemical element with symbol K and atomic number 19. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 63.5,
    boiling: 759,
    density: 0.862,
    yearDiscovered: 1807,
    uses: "Fertilizers, soap, glass",
    isotopes: [
      { mass: 39, neutrons: 20, name: "Potassium-39", abundance: "93.258%", stable: true },
      { mass: 40, neutrons: 21, name: "Potassium-40", abundance: "0.012%", stable: false },
      { mass: 41, neutrons: 22, name: "Potassium-41", abundance: "6.730%", stable: true },
    ],
  },
  {
    name: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    protons: 20,
    neutrons: 20,
    electrons: 20,
    color: 0x74ff00,
    electronColor: 0x8a00ff,
    xpos: 2,
    ypos: 4,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Calcium is a chemical element with symbol Ca and atomic number 20. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 842,
    boiling: 1484,
    density: 1.54,
    yearDiscovered: 1808,
    uses: "Bones, cement, cheese production",
    isotopes: [
      { mass: 40, neutrons: 20, name: "Calcium-40", abundance: "96.941%", stable: true },
      { mass: 42, neutrons: 22, name: "Calcium-42", abundance: "0.647%", stable: true },
      { mass: 43, neutrons: 23, name: "Calcium-43", abundance: "0.135%", stable: true },
      { mass: 44, neutrons: 24, name: "Calcium-44", abundance: "2.086%", stable: true },
      { mass: 48, neutrons: 28, name: "Calcium-48", abundance: "0.187%", stable: true },
    ],
  },
  {
    name: "Scandium",
    symbol: "Sc",
    atomicNumber: 21,
    protons: 21,
    neutrons: 25,
    electrons: 21,
    color: 0x002aff,
    electronColor: 0xffd400,
    xpos: 3,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Scandium is a chemical element with symbol Sc and atomic number 21. It is classified as a Moderate.",
    melting: 1541,
    boiling: 2836,
    density: 2.989,
    yearDiscovered: 1879,
    uses: "Aerospace alloys, sports equipment",
    isotopes: [
      { mass: 45, neutrons: 24, name: "Scandium-45", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Titanium",
    symbol: "Ti",
    atomicNumber: 22,
    protons: 22,
    neutrons: 26,
    electrons: 22,
    color: 0xff1f00,
    electronColor: 0x00dfff,
    xpos: 4,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Titanium is a chemical element with symbol Ti and atomic number 22. It is classified as a Moderate.",
    melting: 1668,
    boiling: 3287,
    density: 4.506,
    yearDiscovered: 1791,
    uses: "Aircraft, medical implants, white paint",
    isotopes: [
      { mass: 46, neutrons: 24, name: "Titanium-46", abundance: "8.25%", stable: true },
      { mass: 47, neutrons: 25, name: "Titanium-47", abundance: "7.44%", stable: true },
      { mass: 48, neutrons: 26, name: "Titanium-48", abundance: "73.72%", stable: true },
      { mass: 49, neutrons: 27, name: "Titanium-49", abundance: "5.41%", stable: true },
      { mass: 50, neutrons: 28, name: "Titanium-50", abundance: "5.18%", stable: true },
    ],
  },
  {
    name: "Vanadium",
    symbol: "V",
    atomicNumber: 23,
    protons: 23,
    neutrons: 27,
    electrons: 23,
    color: 0x00ff6a,
    electronColor: 0xff0094,
    xpos: 5,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Vanadium is a chemical element with symbol V and atomic number 23. It is classified as a Moderate.",
    melting: 1910,
    boiling: 3407,
    density: 6.11,
    yearDiscovered: 1801,
    uses: "Steel alloys, catalysts, batteries",
    isotopes: [
      { mass: 50, neutrons: 27, name: "Vanadium-50", abundance: "0.25%", stable: false },
      { mass: 51, neutrons: 28, name: "Vanadium-51", abundance: "99.75%", stable: true },
    ],
  },
  {
    name: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    protons: 24,
    neutrons: 28,
    electrons: 24,
    color: 0xb400ff,
    electronColor: 0x4aff00,
    xpos: 6,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Chromium is a chemical element with symbol Cr and atomic number 24. It is classified as a Moderate.",
    melting: 1907,
    boiling: 2671,
    density: 7.15,
    yearDiscovered: 1797,
    uses: "Stainless steel, chrome plating, dyes",
    isotopes: [
      { mass: 50, neutrons: 26, name: "Chromium-50", abundance: "4.345%", stable: true },
      { mass: 52, neutrons: 28, name: "Chromium-52", abundance: "83.789%", stable: true },
      { mass: 53, neutrons: 29, name: "Chromium-53", abundance: "9.501%", stable: true },
      { mass: 54, neutrons: 30, name: "Chromium-54", abundance: "2.365%", stable: true },
    ],
  },
  {
    name: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    protons: 25,
    neutrons: 30,
    electrons: 25,
    color: 0xffff00,
    electronColor: 0x0000ff,
    xpos: 7,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Manganese is a chemical element with symbol Mn and atomic number 25. It is classified as a Moderate.",
    melting: 1246,
    boiling: 2061,
    density: 7.44,
    yearDiscovered: 1774,
    uses: "Steel production, batteries, fertilizers",
    isotopes: [
      { mass: 55, neutrons: 30, name: "Manganese-55", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    protons: 26,
    neutrons: 31,
    electrons: 26,
    color: 0x00b4ff,
    electronColor: 0xff4a00,
    xpos: 8,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Iron is a chemical element with symbol Fe and atomic number 26. It is classified as a Moderate.",
    melting: 1538,
    boiling: 2862,
    density: 7.874,
    yearDiscovered: -1200,
    uses: "Steel, construction, machinery, hemoglobin",
    isotopes: [
      { mass: 54, neutrons: 28, name: "Iron-54", abundance: "5.845%", stable: true },
      { mass: 56, neutrons: 30, name: "Iron-56", abundance: "91.754%", stable: true },
      { mass: 57, neutrons: 31, name: "Iron-57", abundance: "2.119%", stable: true },
      { mass: 58, neutrons: 32, name: "Iron-58", abundance: "0.282%", stable: true },
    ],
  },
  {
    name: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    protons: 27,
    neutrons: 32,
    electrons: 27,
    color: 0xff006a,
    electronColor: 0x00ff94,
    xpos: 9,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Cobalt is a chemical element with symbol Co and atomic number 27. It is classified as a Moderate.",
    melting: 1495,
    boiling: 2927,
    density: 8.86,
    yearDiscovered: 1735,
    uses: "Magnets, batteries, blue pigments",
    isotopes: [
      { mass: 59, neutrons: 32, name: "Cobalt-59", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    protons: 28,
    neutrons: 33,
    electrons: 28,
    color: 0x1fff00,
    electronColor: 0xdf00ff,
    xpos: 10,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Nickel is a chemical element with symbol Ni and atomic number 28. It is classified as a Moderate.",
    melting: 1455,
    boiling: 2913,
    density: 8.912,
    yearDiscovered: 1751,
    uses: "Stainless steel, coins, batteries",
    isotopes: [
      { mass: 58, neutrons: 30, name: "Nickel-58", abundance: "68.077%", stable: true },
      { mass: 60, neutrons: 32, name: "Nickel-60", abundance: "26.223%", stable: true },
      { mass: 61, neutrons: 33, name: "Nickel-61", abundance: "1.140%", stable: true },
      { mass: 62, neutrons: 34, name: "Nickel-62", abundance: "3.635%", stable: true },
      { mass: 64, neutrons: 36, name: "Nickel-64", abundance: "0.926%", stable: true },
    ],
  },
  {
    name: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    protons: 29,
    neutrons: 34,
    electrons: 29,
    color: 0x2a00ff,
    electronColor: 0xd4ff00,
    xpos: 11,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Copper is a chemical element with symbol Cu and atomic number 29. It is classified as a Moderate.",
    melting: 1084.62,
    boiling: 2562,
    density: 8.96,
    yearDiscovered: -9000,
    uses: "Electrical wiring, plumbing, coins",
    isotopes: [
      { mass: 63, neutrons: 34, name: "Copper-63", abundance: "69.15%", stable: true },
      { mass: 65, neutrons: 36, name: "Copper-65", abundance: "30.85%", stable: true },
    ],
  },
  {
    name: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    protons: 30,
    neutrons: 36,
    electrons: 30,
    color: 0xff7400,
    electronColor: 0x008aff,
    xpos: 12,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Zinc is a chemical element with symbol Zn and atomic number 30. It is classified as a Moderate.",
    melting: 419.53,
    boiling: 907,
    density: 7.134,
    yearDiscovered: 1746,
    uses: "Galvanizing, brass, batteries",
    isotopes: [
      { mass: 64, neutrons: 34, name: "Zinc-64", abundance: "49.17%", stable: true },
      { mass: 66, neutrons: 36, name: "Zinc-66", abundance: "27.73%", stable: true },
      { mass: 67, neutrons: 37, name: "Zinc-67", abundance: "4.04%", stable: true },
      { mass: 68, neutrons: 38, name: "Zinc-68", abundance: "18.45%", stable: true },
      { mass: 70, neutrons: 40, name: "Zinc-70", abundance: "0.61%", stable: true },
    ],
  },
  {
    name: "Gallium",
    symbol: "Ga",
    atomicNumber: 31,
    protons: 31,
    neutrons: 37,
    electrons: 31,
    color: 0x00ffbf,
    electronColor: 0xff003f,
    xpos: 13,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Gallium is a chemical element with symbol Ga and atomic number 31. It is classified as a Moderate.",
    melting: 29.76,
    boiling: 2204,
    density: 5.907,
    yearDiscovered: 1875,
    uses: "Semiconductors, LEDs, solar cells",
    isotopes: [
      { mass: 69, neutrons: 38, name: "Gallium-69", abundance: "60.108%", stable: true },
      { mass: 71, neutrons: 40, name: "Gallium-71", abundance: "39.892%", stable: true },
    ],
  },
  {
    name: "Germanium",
    symbol: "Ge",
    atomicNumber: 32,
    protons: 32,
    neutrons: 38,
    electrons: 32,
    color: 0xff00f4,
    electronColor: 0x00ff0a,
    xpos: 14,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Germanium is a chemical element with symbol Ge and atomic number 32. It is classified as a Moderate.",
    melting: 938.25,
    boiling: 2833,
    density: 5.323,
    yearDiscovered: 1886,
    uses: "Fiber optics, infrared optics, transistors",
    isotopes: [
      { mass: 70, neutrons: 38, name: "Germanium-70", abundance: "20.84%", stable: true },
      { mass: 72, neutrons: 40, name: "Germanium-72", abundance: "27.54%", stable: true },
      { mass: 73, neutrons: 41, name: "Germanium-73", abundance: "7.73%", stable: true },
      { mass: 74, neutrons: 42, name: "Germanium-74", abundance: "36.28%", stable: true },
      { mass: 76, neutrons: 44, name: "Germanium-76", abundance: "7.61%", stable: true },
    ],
  },
  {
    name: "Arsenic",
    symbol: "As",
    atomicNumber: 33,
    protons: 33,
    neutrons: 39,
    electrons: 33,
    color: 0xaaff00,
    electronColor: 0x5400ff,
    xpos: 15,
    ypos: 4,
    reactivity: "Moderate",
    isReactive: false,
    description: "Arsenic is a chemical element with symbol As and atomic number 33. It is classified as a Moderate.",
    melting: 817,
    boiling: 614,
    density: 5.776,
    yearDiscovered: 1250,
    uses: "Semiconductors, wood preservatives, pesticides",
    isotopes: [
      { mass: 75, neutrons: 42, name: "Arsenic-75", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    protons: 34,
    neutrons: 40,
    electrons: 34,
    color: 0x005fff,
    electronColor: 0xff9f00,
    xpos: 16,
    ypos: 4,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Selenium is a chemical element with symbol Se and atomic number 34. It is classified as a Chalcogen (Reactive).",
    melting: 221,
    boiling: 685,
    density: 4.809,
    yearDiscovered: 1817,
    uses: "Glass manufacturing, electronics, photocopiers",
    isotopes: [
      { mass: 74, neutrons: 40, name: "Selenium-74", abundance: "0.89%", stable: true },
      { mass: 76, neutrons: 42, name: "Selenium-76", abundance: "9.37%", stable: true },
      { mass: 77, neutrons: 43, name: "Selenium-77", abundance: "7.63%", stable: true },
      { mass: 78, neutrons: 44, name: "Selenium-78", abundance: "23.77%", stable: true },
      { mass: 80, neutrons: 46, name: "Selenium-80", abundance: "49.61%", stable: true },
      { mass: 82, neutrons: 48, name: "Selenium-82", abundance: "8.73%", stable: true },
    ],
  },
  {
    name: "Bromine",
    symbol: "Br",
    atomicNumber: 35,
    protons: 35,
    neutrons: 42,
    electrons: 35,
    color: 0xff0015,
    electronColor: 0x00ffe9,
    xpos: 17,
    ypos: 4,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Bromine is a chemical element with symbol Br and atomic number 35. It is classified as a Halogen (Highly Reactive).",
    melting: -7.2,
    boiling: 58.8,
    density: 3.122,
    yearDiscovered: 1826,
    uses: "Flame retardants, water treatment, photography",
    isotopes: [
      { mass: 79, neutrons: 44, name: "Bromine-79", abundance: "50.69%", stable: true },
      { mass: 81, neutrons: 46, name: "Bromine-81", abundance: "49.31%", stable: true },
    ],
  },
  {
    name: "Krypton",
    symbol: "Kr",
    atomicNumber: 36,
    protons: 36,
    neutrons: 43,
    electrons: 36,
    color: 0x00ff35,
    electronColor: 0xff00c9,
    xpos: 18,
    ypos: 4,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Krypton is a chemical element with symbol Kr and atomic number 36. It is classified as a Noble Gas (Inert).",
    melting: -157.36,
    boiling: -153.22,
    density: 0.003733,
    yearDiscovered: 1898,
    uses: "Lighting, lasers, insulation",
    isotopes: [
      { mass: 78, neutrons: 42, name: "Krypton-78", abundance: "0.35%", stable: true },
      { mass: 80, neutrons: 44, name: "Krypton-80", abundance: "2.28%", stable: true },
      { mass: 82, neutrons: 46, name: "Krypton-82", abundance: "11.58%", stable: true },
      { mass: 83, neutrons: 47, name: "Krypton-83", abundance: "11.49%", stable: true },
      { mass: 84, neutrons: 48, name: "Krypton-84", abundance: "57.00%", stable: true },
      { mass: 86, neutrons: 50, name: "Krypton-86", abundance: "17.30%", stable: true },
    ],
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    atomicNumber: 37,
    protons: 37,
    neutrons: 44,
    electrons: 37,
    color: 0x7f00ff,
    electronColor: 0x7fff00,
    xpos: 1,
    ypos: 5,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Rubidium is a chemical element with symbol Rb and atomic number 37. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 39.31,
    boiling: 688,
    density: 1.532,
    yearDiscovered: 1861,
    uses: "Atomic clocks, photocells, research",
    isotopes: [
      { mass: 85, neutrons: 48, name: "Rubidium-85", abundance: "72.17%", stable: true },
      { mass: 87, neutrons: 50, name: "Rubidium-87", abundance: "27.83%", stable: false },
    ],
  },
  {
    name: "Strontium",
    symbol: "Sr",
    atomicNumber: 38,
    protons: 38,
    neutrons: 45,
    electrons: 38,
    color: 0xffc900,
    electronColor: 0x0035ff,
    xpos: 2,
    ypos: 5,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Strontium is a chemical element with symbol Sr and atomic number 38. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 777,
    boiling: 1382,
    density: 2.64,
    yearDiscovered: 1790,
    uses: "Fireworks, flares, magnets",
    isotopes: [
      { mass: 84, neutrons: 46, name: "Strontium-84", abundance: "0.56%", stable: true },
      { mass: 86, neutrons: 48, name: "Strontium-86", abundance: "9.86%", stable: true },
      { mass: 87, neutrons: 49, name: "Strontium-87", abundance: "7.00%", stable: true },
      { mass: 88, neutrons: 50, name: "Strontium-88", abundance: "82.58%", stable: true },
    ],
  },
  {
    name: "Yttrium",
    symbol: "Y",
    atomicNumber: 39,
    protons: 39,
    neutrons: 46,
    electrons: 39,
    color: 0x00e9ff,
    electronColor: 0xff1500,
    xpos: 3,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Yttrium is a chemical element with symbol Y and atomic number 39. It is classified as a Moderate.",
    melting: 1526,
    boiling: 3345,
    density: 4.469,
    yearDiscovered: 1794,
    uses: "LEDs, superconductors, cancer treatment",
    isotopes: [
      { mass: 89, neutrons: 50, name: "Yttrium-89", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    atomicNumber: 40,
    protons: 40,
    neutrons: 48,
    electrons: 40,
    color: 0xff009f,
    electronColor: 0x00ff5f,
    xpos: 4,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Zirconium is a chemical element with symbol Zr and atomic number 40. It is classified as a Moderate.",
    melting: 1855,
    boiling: 4409,
    density: 6.506,
    yearDiscovered: 1789,
    uses: "Nuclear reactors, ceramics, gems",
    isotopes: [
      { mass: 90, neutrons: 50, name: "Zirconium-90", abundance: "51.45%", stable: true },
      { mass: 91, neutrons: 51, name: "Zirconium-91", abundance: "11.22%", stable: true },
      { mass: 92, neutrons: 52, name: "Zirconium-92", abundance: "17.15%", stable: true },
      { mass: 94, neutrons: 54, name: "Zirconium-94", abundance: "17.38%", stable: true },
      { mass: 96, neutrons: 56, name: "Zirconium-96", abundance: "2.80%", stable: true },
    ],
  },
  {
    name: "Niobium",
    symbol: "Nb",
    atomicNumber: 41,
    protons: 41,
    neutrons: 49,
    electrons: 41,
    color: 0x54ff00,
    electronColor: 0xaa00ff,
    xpos: 5,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Niobium is a chemical element with symbol Nb and atomic number 41. It is classified as a Moderate.",
    melting: 2477,
    boiling: 4744,
    density: 8.57,
    yearDiscovered: 1801,
    uses: "Superconductors, steel alloys, jewelry",
    isotopes: [
      { mass: 93, neutrons: 52, name: "Niobium-93", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    protons: 42,
    neutrons: 50,
    electrons: 42,
    color: 0x000aff,
    electronColor: 0xfff400,
    xpos: 6,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Molybdenum is a chemical element with symbol Mo and atomic number 42. It is classified as a Moderate.",
    melting: 2623,
    boiling: 4639,
    density: 10.22,
    yearDiscovered: 1778,
    uses: "Steel alloys, lubricants, catalysts",
    isotopes: [
      { mass: 92, neutrons: 50, name: "Molybdenum-92", abundance: "14.84%", stable: true },
      { mass: 94, neutrons: 52, name: "Molybdenum-94", abundance: "9.25%", stable: true },
      { mass: 95, neutrons: 53, name: "Molybdenum-95", abundance: "15.92%", stable: true },
      { mass: 96, neutrons: 54, name: "Molybdenum-96", abundance: "16.68%", stable: true },
      { mass: 97, neutrons: 55, name: "Molybdenum-97", abundance: "9.55%", stable: true },
      { mass: 98, neutrons: 56, name: "Molybdenum-98", abundance: "24.13%", stable: true },
      { mass: 100, neutrons: 58, name: "Molybdenum-100", abundance: "9.63%", stable: true },
    ],
  },
  {
    name: "Technetium",
    symbol: "Tc",
    atomicNumber: 43,
    protons: 43,
    neutrons: 51,
    electrons: 43,
    color: 0xff3f00,
    electronColor: 0x00bfff,
    xpos: 7,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Technetium is a chemical element with symbol Tc and atomic number 43. It is classified as a Moderate.",
    melting: 2157,
    boiling: 4265,
    density: 11.5,
    yearDiscovered: 1937,
    uses: "Medical imaging, corrosion inhibitor",
    isotopes: [
      { mass: 97, neutrons: 54, name: "Technetium-97", abundance: "trace", stable: false },
      { mass: 98, neutrons: 55, name: "Technetium-98", abundance: "trace", stable: false },
      { mass: 99, neutrons: 56, name: "Technetium-99", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    atomicNumber: 44,
    protons: 44,
    neutrons: 52,
    electrons: 44,
    color: 0x00ff8a,
    electronColor: 0xff0074,
    xpos: 8,
    ypos: 5,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is classified as a Noble Metal (Unreactive).",
    melting: 2334,
    boiling: 4150,
    density: 12.37,
    yearDiscovered: 1844,
    uses: "Electronics, catalysts, alloys",
    isotopes: [
      { mass: 96, neutrons: 52, name: "Ruthenium-96", abundance: "5.54%", stable: true },
      { mass: 98, neutrons: 54, name: "Ruthenium-98", abundance: "1.87%", stable: true },
      { mass: 99, neutrons: 55, name: "Ruthenium-99", abundance: "12.76%", stable: true },
      { mass: 100, neutrons: 56, name: "Ruthenium-100", abundance: "12.60%", stable: true },
      { mass: 101, neutrons: 57, name: "Ruthenium-101", abundance: "17.06%", stable: true },
      { mass: 102, neutrons: 58, name: "Ruthenium-102", abundance: "31.55%", stable: true },
      { mass: 104, neutrons: 60, name: "Ruthenium-104", abundance: "18.62%", stable: true },
    ],
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    atomicNumber: 45,
    protons: 45,
    neutrons: 54,
    electrons: 45,
    color: 0xd400ff,
    electronColor: 0x2aff00,
    xpos: 9,
    ypos: 5,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is classified as a Noble Metal (Unreactive).",
    melting: 1964,
    boiling: 3695,
    density: 12.41,
    yearDiscovered: 1803,
    uses: "Catalytic converters, jewelry, mirrors",
    isotopes: [
      { mass: 103, neutrons: 58, name: "Rhodium-103", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Palladium",
    symbol: "Pd",
    atomicNumber: 46,
    protons: 46,
    neutrons: 55,
    electrons: 46,
    color: 0xdfff00,
    electronColor: 0x1f00ff,
    xpos: 10,
    ypos: 5,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Palladium is a chemical element with symbol Pd and atomic number 46. It is classified as a Noble Metal (Unreactive).",
    melting: 1554.9,
    boiling: 2963,
    density: 12.02,
    yearDiscovered: 1803,
    uses: "Catalytic converters, electronics, dentistry",
    isotopes: [
      { mass: 102, neutrons: 56, name: "Palladium-102", abundance: "1.02%", stable: true },
      { mass: 104, neutrons: 58, name: "Palladium-104", abundance: "11.14%", stable: true },
      { mass: 105, neutrons: 59, name: "Palladium-105", abundance: "22.33%", stable: true },
      { mass: 106, neutrons: 60, name: "Palladium-106", abundance: "27.33%", stable: true },
      { mass: 108, neutrons: 62, name: "Palladium-108", abundance: "26.46%", stable: true },
      { mass: 110, neutrons: 64, name: "Palladium-110", abundance: "11.72%", stable: true },
    ],
  },
  {
    name: "Silver",
    symbol: "Ag",
    atomicNumber: 47,
    protons: 47,
    neutrons: 56,
    electrons: 47,
    color: 0x0094ff,
    electronColor: 0xff6a00,
    xpos: 11,
    ypos: 5,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Silver is a chemical element with symbol Ag and atomic number 47. It is classified as a Noble Metal (Unreactive).",
    melting: 961.78,
    boiling: 2162,
    density: 10.501,
    yearDiscovered: -3000,
    uses: "Jewelry, coins, photography, electronics",
    isotopes: [
      { mass: 107, neutrons: 60, name: "Silver-107", abundance: "51.839%", stable: true },
      { mass: 109, neutrons: 62, name: "Silver-109", abundance: "48.161%", stable: true },
    ],
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    atomicNumber: 48,
    protons: 48,
    neutrons: 57,
    electrons: 48,
    color: 0xff004a,
    electronColor: 0x00ffb4,
    xpos: 12,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Cadmium is a chemical element with symbol Cd and atomic number 48. It is classified as a Moderate.",
    melting: 321.07,
    boiling: 767,
    density: 8.69,
    yearDiscovered: 1817,
    uses: "Batteries, pigments, coatings",
    isotopes: [
      { mass: 106, neutrons: 58, name: "Cadmium-106", abundance: "1.25%", stable: true },
      { mass: 108, neutrons: 60, name: "Cadmium-108", abundance: "0.89%", stable: true },
      { mass: 110, neutrons: 62, name: "Cadmium-110", abundance: "12.49%", stable: true },
      { mass: 111, neutrons: 63, name: "Cadmium-111", abundance: "12.80%", stable: true },
      { mass: 112, neutrons: 64, name: "Cadmium-112", abundance: "24.13%", stable: true },
      { mass: 113, neutrons: 65, name: "Cadmium-113", abundance: "12.22%", stable: true },
      { mass: 114, neutrons: 66, name: "Cadmium-114", abundance: "28.73%", stable: true },
      { mass: 116, neutrons: 68, name: "Cadmium-116", abundance: "7.49%", stable: true },
    ],
  },
  {
    name: "Indium",
    symbol: "In",
    atomicNumber: 49,
    protons: 49,
    neutrons: 58,
    electrons: 49,
    color: 0x00ff00,
    electronColor: 0xff00ff,
    xpos: 13,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Indium is a chemical element with symbol In and atomic number 49. It is classified as a Moderate.",
    melting: 156.6,
    boiling: 2072,
    density: 7.31,
    yearDiscovered: 1863,
    uses: "Touch screens, solar panels, LEDs",
    isotopes: [
      { mass: 113, neutrons: 64, name: "Indium-113", abundance: "4.29%", stable: true },
      { mass: 115, neutrons: 66, name: "Indium-115", abundance: "95.71%", stable: false },
    ],
  },
  {
    name: "Tin",
    symbol: "Sn",
    atomicNumber: 50,
    protons: 50,
    neutrons: 60,
    electrons: 50,
    color: 0x4a00ff,
    electronColor: 0xb4ff00,
    xpos: 14,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Tin is a chemical element with symbol Sn and atomic number 50. It is classified as a Moderate.",
    melting: 231.93,
    boiling: 2602,
    density: 7.287,
    yearDiscovered: -3500,
    uses: "Solder, tin cans, bronze",
    isotopes: [
      { mass: 112, neutrons: 62, name: "Tin-112", abundance: "0.97%", stable: true },
      { mass: 114, neutrons: 64, name: "Tin-114", abundance: "0.66%", stable: true },
      { mass: 115, neutrons: 65, name: "Tin-115", abundance: "0.34%", stable: true },
      { mass: 116, neutrons: 66, name: "Tin-116", abundance: "14.54%", stable: true },
      { mass: 117, neutrons: 67, name: "Tin-117", abundance: "7.68%", stable: true },
      { mass: 118, neutrons: 68, name: "Tin-118", abundance: "24.22%", stable: true },
      { mass: 119, neutrons: 69, name: "Tin-119", abundance: "8.59%", stable: true },
      { mass: 120, neutrons: 70, name: "Tin-120", abundance: "32.58%", stable: true },
      { mass: 122, neutrons: 72, name: "Tin-122", abundance: "4.63%", stable: true },
      { mass: 124, neutrons: 74, name: "Tin-124", abundance: "5.79%", stable: true },
    ],
  },
  {
    name: "Antimony",
    symbol: "Sb",
    atomicNumber: 51,
    protons: 51,
    neutrons: 71,
    electrons: 51,
    color: 0xff9400,
    electronColor: 0x006aff,
    xpos: 15,
    ypos: 5,
    reactivity: "Moderate",
    isReactive: false,
    description: "Antimony is a chemical element with symbol Sb and atomic number 51. It is classified as a Moderate.",
    melting: 630.63,
    boiling: 1587,
    density: 6.685,
    yearDiscovered: 1450,
    uses: "Flame retardants, batteries, semiconductors",
    isotopes: [
      { mass: 121, neutrons: 70, name: "Antimony-121", abundance: "57.21%", stable: true },
      { mass: 123, neutrons: 72, name: "Antimony-123", abundance: "42.79%", stable: true },
    ],
  },
  {
    name: "Tellurium",
    symbol: "Te",
    atomicNumber: 52,
    protons: 52,
    neutrons: 72,
    electrons: 52,
    color: 0x00ffdf,
    electronColor: 0xff001f,
    xpos: 16,
    ypos: 5,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Tellurium is a chemical element with symbol Te and atomic number 52. It is classified as a Chalcogen (Reactive).",
    melting: 449.51,
    boiling: 988,
    density: 6.232,
    yearDiscovered: 1783,
    uses: "Solar cells, thermoelectrics, metallurgy",
    isotopes: [
      { mass: 120, neutrons: 68, name: "Tellurium-120", abundance: "0.09%", stable: true },
      { mass: 122, neutrons: 70, name: "Tellurium-122", abundance: "2.55%", stable: true },
      { mass: 123, neutrons: 71, name: "Tellurium-123", abundance: "0.89%", stable: true },
      { mass: 124, neutrons: 72, name: "Tellurium-124", abundance: "4.74%", stable: true },
      { mass: 125, neutrons: 73, name: "Tellurium-125", abundance: "7.07%", stable: true },
      { mass: 126, neutrons: 74, name: "Tellurium-126", abundance: "18.84%", stable: true },
      { mass: 128, neutrons: 76, name: "Tellurium-128", abundance: "31.74%", stable: true },
      { mass: 130, neutrons: 78, name: "Tellurium-130", abundance: "34.08%", stable: true },
    ],
  },
  {
    name: "Iodine",
    symbol: "I",
    atomicNumber: 53,
    protons: 53,
    neutrons: 74,
    electrons: 53,
    color: 0xff00d4,
    electronColor: 0x00ff2a,
    xpos: 17,
    ypos: 5,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Iodine is a chemical element with symbol I and atomic number 53. It is classified as a Halogen (Highly Reactive).",
    melting: 113.7,
    boiling: 184.3,
    density: 4.93,
    yearDiscovered: 1811,
    uses: "Disinfectants, pharmaceuticals, photography",
    isotopes: [
      { mass: 127, neutrons: 74, name: "Iodine-127", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Xenon",
    symbol: "Xe",
    atomicNumber: 54,
    protons: 54,
    neutrons: 75,
    electrons: 54,
    color: 0x8aff00,
    electronColor: 0x7400ff,
    xpos: 18,
    ypos: 5,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Xenon is a chemical element with symbol Xe and atomic number 54. It is classified as a Noble Gas (Inert).",
    melting: -111.75,
    boiling: -108.04,
    density: 0.005887,
    yearDiscovered: 1898,
    uses: "Lighting, anesthesia, ion propulsion",
    isotopes: [
      { mass: 124, neutrons: 70, name: "Xenon-124", abundance: "0.095%", stable: true },
      { mass: 126, neutrons: 72, name: "Xenon-126", abundance: "0.089%", stable: true },
      { mass: 128, neutrons: 74, name: "Xenon-128", abundance: "1.910%", stable: true },
      { mass: 129, neutrons: 75, name: "Xenon-129", abundance: "26.401%", stable: true },
      { mass: 130, neutrons: 76, name: "Xenon-130", abundance: "4.071%", stable: true },
      { mass: 131, neutrons: 77, name: "Xenon-131", abundance: "21.232%", stable: true },
      { mass: 132, neutrons: 78, name: "Xenon-132", abundance: "26.909%", stable: true },
      { mass: 134, neutrons: 80, name: "Xenon-134", abundance: "10.436%", stable: true },
      { mass: 136, neutrons: 82, name: "Xenon-136", abundance: "8.857%", stable: true },
    ],
  },
  {
    name: "Cesium",
    symbol: "Cs",
    atomicNumber: 55,
    protons: 55,
    neutrons: 77,
    electrons: 55,
    color: 0x003fff,
    electronColor: 0xffbf00,
    xpos: 1,
    ypos: 6,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Cesium is a chemical element with symbol Cs and atomic number 55. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 28.44,
    boiling: 671,
    density: 1.873,
    yearDiscovered: 1860,
    uses: "Atomic clocks, drilling fluids, photoelectric cells",
    isotopes: [
      { mass: 133, neutrons: 78, name: "Cesium-133", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Barium",
    symbol: "Ba",
    atomicNumber: 56,
    protons: 56,
    neutrons: 78,
    electrons: 56,
    color: 0xff0a00,
    electronColor: 0x00f4ff,
    xpos: 2,
    ypos: 6,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Barium is a chemical element with symbol Ba and atomic number 56. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 727,
    boiling: 1870,
    density: 3.594,
    yearDiscovered: 1808,
    uses: "Medical imaging, fireworks, drilling fluids",
    isotopes: [
      { mass: 130, neutrons: 74, name: "Barium-130", abundance: "0.106%", stable: true },
      { mass: 132, neutrons: 76, name: "Barium-132", abundance: "0.101%", stable: true },
      { mass: 134, neutrons: 78, name: "Barium-134", abundance: "2.417%", stable: true },
      { mass: 135, neutrons: 79, name: "Barium-135", abundance: "6.592%", stable: true },
      { mass: 136, neutrons: 80, name: "Barium-136", abundance: "7.854%", stable: true },
      { mass: 137, neutrons: 81, name: "Barium-137", abundance: "11.232%", stable: true },
      { mass: 138, neutrons: 82, name: "Barium-138", abundance: "71.698%", stable: true },
    ],
  },
  {
    name: "Lanthanum",
    symbol: "La",
    atomicNumber: 57,
    protons: 57,
    neutrons: 79,
    electrons: 57,
    color: 0x00ff55,
    electronColor: 0xff00aa,
    xpos: 3,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Lanthanum is a chemical element with symbol La and atomic number 57. It is classified as a Radioactive/Reactive.",
    melting: 918,
    boiling: 3464,
    density: 6.145,
    yearDiscovered: 1839,
    uses: "Camera lenses, lighting, batteries",
    isotopes: [
      { mass: 138, neutrons: 81, name: "Lanthanum-138", abundance: "0.09%", stable: false },
      { mass: 139, neutrons: 82, name: "Lanthanum-139", abundance: "99.91%", stable: true },
    ],
  },
  {
    name: "Cerium",
    symbol: "Ce",
    atomicNumber: 58,
    protons: 58,
    neutrons: 81,
    electrons: 58,
    color: 0x9f00ff,
    electronColor: 0x5fff00,
    xpos: 4,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Cerium is a chemical element with symbol Ce and atomic number 58. It is classified as a Radioactive/Reactive.",
    melting: 798,
    boiling: 3443,
    density: 6.77,
    yearDiscovered: 1803,
    uses: "Catalytic converters, lighter flints, glass polishing",
    isotopes: [
      { mass: 136, neutrons: 78, name: "Cerium-136", abundance: "0.185%", stable: true },
      { mass: 138, neutrons: 80, name: "Cerium-138", abundance: "0.251%", stable: true },
      { mass: 140, neutrons: 82, name: "Cerium-140", abundance: "88.450%", stable: true },
      { mass: 142, neutrons: 84, name: "Cerium-142", abundance: "11.114%", stable: true },
    ],
  },
  {
    name: "Praseodymium",
    symbol: "Pr",
    atomicNumber: 59,
    protons: 59,
    neutrons: 82,
    electrons: 59,
    color: 0xffe900,
    electronColor: 0x0015ff,
    xpos: 5,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is classified as a Radioactive/Reactive.",
    melting: 931,
    boiling: 3520,
    density: 6.773,
    yearDiscovered: 1885,
    uses: "Magnets, lasers, arc lighting",
    isotopes: [
      { mass: 141, neutrons: 82, name: "Praseodymium-141", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Neodymium",
    symbol: "Nd",
    atomicNumber: 60,
    protons: 60,
    neutrons: 84,
    electrons: 60,
    color: 0x00c9ff,
    electronColor: 0xff3500,
    xpos: 6,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is classified as a Radioactive/Reactive.",
    melting: 1021,
    boiling: 3074,
    density: 7.007,
    yearDiscovered: 1885,
    uses: "Powerful magnets, lasers, glass coloring",
    isotopes: [
      { mass: 142, neutrons: 82, name: "Neodymium-142", abundance: "27.2%", stable: true },
      { mass: 143, neutrons: 83, name: "Neodymium-143", abundance: "12.2%", stable: true },
      { mass: 144, neutrons: 84, name: "Neodymium-144", abundance: "23.8%", stable: true },
      { mass: 145, neutrons: 85, name: "Neodymium-145", abundance: "8.3%", stable: true },
      { mass: 146, neutrons: 86, name: "Neodymium-146", abundance: "17.2%", stable: true },
      { mass: 148, neutrons: 88, name: "Neodymium-148", abundance: "5.7%", stable: true },
      { mass: 150, neutrons: 90, name: "Neodymium-150", abundance: "5.6%", stable: true },
    ],
  },
  {
    name: "Promethium",
    symbol: "Pm",
    atomicNumber: 61,
    protons: 61,
    neutrons: 85,
    electrons: 61,
    color: 0xff007f,
    electronColor: 0x00ff7f,
    xpos: 7,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Promethium is a chemical element with symbol Pm and atomic number 61. It is classified as a Radioactive/Reactive.",
    melting: 1042,
    boiling: 3000,
    density: 7.26,
    yearDiscovered: 1945,
    uses: "Luminous paint, atomic batteries, thickness gauges",
    isotopes: [
      { mass: 145, neutrons: 84, name: "Promethium-145", abundance: "trace", stable: false },
      { mass: 147, neutrons: 86, name: "Promethium-147", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Samarium",
    symbol: "Sm",
    atomicNumber: 62,
    protons: 62,
    neutrons: 86,
    electrons: 62,
    color: 0x35ff00,
    electronColor: 0xc900ff,
    xpos: 8,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Samarium is a chemical element with symbol Sm and atomic number 62. It is classified as a Radioactive/Reactive.",
    melting: 1072,
    boiling: 1794,
    density: 7.52,
    yearDiscovered: 1879,
    uses: "Magnets, lasers, nuclear reactors",
    isotopes: [
      { mass: 144, neutrons: 82, name: "Samarium-144", abundance: "3.07%", stable: true },
      { mass: 147, neutrons: 85, name: "Samarium-147", abundance: "14.99%", stable: false },
      { mass: 148, neutrons: 86, name: "Samarium-148", abundance: "11.24%", stable: false },
      { mass: 149, neutrons: 87, name: "Samarium-149", abundance: "13.82%", stable: true },
      { mass: 150, neutrons: 88, name: "Samarium-150", abundance: "7.38%", stable: true },
      { mass: 152, neutrons: 90, name: "Samarium-152", abundance: "26.75%", stable: true },
      { mass: 154, neutrons: 92, name: "Samarium-154", abundance: "22.75%", stable: true },
    ],
  },
  {
    name: "Europium",
    symbol: "Eu",
    atomicNumber: 63,
    protons: 63,
    neutrons: 88,
    electrons: 63,
    color: 0x1500ff,
    electronColor: 0xe9ff00,
    xpos: 9,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Europium is a chemical element with symbol Eu and atomic number 63. It is classified as a Radioactive/Reactive.",
    melting: 822,
    boiling: 1529,
    density: 5.243,
    yearDiscovered: 1901,
    uses: "Phosphors, lasers, nuclear control rods",
    isotopes: [
      { mass: 151, neutrons: 88, name: "Europium-151", abundance: "47.81%", stable: true },
      { mass: 153, neutrons: 90, name: "Europium-153", abundance: "52.19%", stable: true },
    ],
  },
  {
    name: "Gadolinium",
    symbol: "Gd",
    atomicNumber: 64,
    protons: 64,
    neutrons: 89,
    electrons: 64,
    color: 0xff5f00,
    electronColor: 0x009fff,
    xpos: 10,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is classified as a Radioactive/Reactive.",
    melting: 1313,
    boiling: 3273,
    density: 7.895,
    yearDiscovered: 1880,
    uses: "MRI contrast agents, magnets, neutron capture",
    isotopes: [
      { mass: 152, neutrons: 88, name: "Gadolinium-152", abundance: "0.20%", stable: false },
      { mass: 154, neutrons: 90, name: "Gadolinium-154", abundance: "2.18%", stable: true },
      { mass: 155, neutrons: 91, name: "Gadolinium-155", abundance: "14.80%", stable: true },
      { mass: 156, neutrons: 92, name: "Gadolinium-156", abundance: "20.47%", stable: true },
      { mass: 157, neutrons: 93, name: "Gadolinium-157", abundance: "15.65%", stable: true },
      { mass: 158, neutrons: 94, name: "Gadolinium-158", abundance: "24.84%", stable: true },
      { mass: 160, neutrons: 96, name: "Gadolinium-160", abundance: "21.86%", stable: true },
    ],
  },
  {
    name: "Terbium",
    symbol: "Tb",
    atomicNumber: 65,
    protons: 65,
    neutrons: 91,
    electrons: 65,
    color: 0x00ffa9,
    electronColor: 0xff0055,
    xpos: 11,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Terbium is a chemical element with symbol Tb and atomic number 65. It is classified as a Radioactive/Reactive.",
    melting: 1356,
    boiling: 3230,
    density: 8.229,
    yearDiscovered: 1843,
    uses: "Phosphors, magnets, fuel cells",
    isotopes: [
      { mass: 159, neutrons: 94, name: "Terbium-159", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Dysprosium",
    symbol: "Dy",
    atomicNumber: 66,
    protons: 66,
    neutrons: 92,
    electrons: 66,
    color: 0xf400ff,
    electronColor: 0x0aff00,
    xpos: 12,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is classified as a Radioactive/Reactive.",
    melting: 1412,
    boiling: 2567,
    density: 8.55,
    yearDiscovered: 1886,
    uses: "Magnets, lasers, nuclear reactors",
    isotopes: [
      { mass: 156, neutrons: 90, name: "Dysprosium-156", abundance: "0.06%", stable: true },
      { mass: 158, neutrons: 92, name: "Dysprosium-158", abundance: "0.10%", stable: true },
      { mass: 160, neutrons: 94, name: "Dysprosium-160", abundance: "2.34%", stable: true },
      { mass: 161, neutrons: 95, name: "Dysprosium-161", abundance: "18.91%", stable: true },
      { mass: 162, neutrons: 96, name: "Dysprosium-162", abundance: "25.51%", stable: true },
      { mass: 163, neutrons: 97, name: "Dysprosium-163", abundance: "24.90%", stable: true },
      { mass: 164, neutrons: 98, name: "Dysprosium-164", abundance: "28.18%", stable: true },
    ],
  },
  {
    name: "Holmium",
    symbol: "Ho",
    atomicNumber: 67,
    protons: 67,
    neutrons: 93,
    electrons: 67,
    color: 0xbfff00,
    electronColor: 0x3f00ff,
    xpos: 13,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Holmium is a chemical element with symbol Ho and atomic number 67. It is classified as a Radioactive/Reactive.",
    melting: 1474,
    boiling: 2700,
    density: 8.795,
    yearDiscovered: 1878,
    uses: "Lasers, magnets, nuclear reactors",
    isotopes: [
      { mass: 165, neutrons: 98, name: "Holmium-165", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Erbium",
    symbol: "Er",
    atomicNumber: 68,
    protons: 68,
    neutrons: 95,
    electrons: 68,
    color: 0x0074ff,
    electronColor: 0xff8a00,
    xpos: 14,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Erbium is a chemical element with symbol Er and atomic number 68. It is classified as a Radioactive/Reactive.",
    melting: 1529,
    boiling: 2868,
    density: 9.066,
    yearDiscovered: 1843,
    uses: "Fiber optics, lasers, nuclear technology",
    isotopes: [
      { mass: 162, neutrons: 94, name: "Erbium-162", abundance: "0.14%", stable: true },
      { mass: 164, neutrons: 96, name: "Erbium-164", abundance: "1.61%", stable: true },
      { mass: 166, neutrons: 98, name: "Erbium-166", abundance: "33.61%", stable: true },
      { mass: 167, neutrons: 99, name: "Erbium-167", abundance: "22.93%", stable: true },
      { mass: 168, neutrons: 100, name: "Erbium-168", abundance: "26.78%", stable: true },
      { mass: 170, neutrons: 102, name: "Erbium-170", abundance: "14.93%", stable: true },
    ],
  },
  {
    name: "Thulium",
    symbol: "Tm",
    atomicNumber: 69,
    protons: 69,
    neutrons: 96,
    electrons: 69,
    color: 0xff002a,
    electronColor: 0x00ffd4,
    xpos: 15,
    ypos: 8,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Thulium is a chemical element with symbol Tm and atomic number 69. It is classified as a Radioactive/Reactive.",
    melting: 1545,
    boiling: 1950,
    density: 9.321,
    yearDiscovered: 1879,
    uses: "Portable X-ray devices, lasers, alloys",
    isotopes: [
      { mass: 169, neutrons: 100, name: "Thulium-169", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Ytterbium",
    symbol: "Yb",
    atomicNumber: 70,
    protons: 70,
    neutrons: 98,
    electrons: 70,
    color: 0x00ff1f,
    electronColor: 0xff00df,
    xpos: 16,
    ypos: 8,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is classified as a Chalcogen (Reactive).",
    melting: 824,
    boiling: 1196,
    density: 6.965,
    yearDiscovered: 1878,
    uses: "Lasers, metallurgy, stress gauges",
    isotopes: [
      { mass: 168, neutrons: 98, name: "Ytterbium-168", abundance: "0.13%", stable: true },
      { mass: 170, neutrons: 100, name: "Ytterbium-170", abundance: "3.04%", stable: true },
      { mass: 171, neutrons: 101, name: "Ytterbium-171", abundance: "14.28%", stable: true },
      { mass: 172, neutrons: 102, name: "Ytterbium-172", abundance: "21.83%", stable: true },
      { mass: 173, neutrons: 103, name: "Ytterbium-173", abundance: "16.13%", stable: true },
      { mass: 174, neutrons: 104, name: "Ytterbium-174", abundance: "31.83%", stable: true },
      { mass: 176, neutrons: 106, name: "Ytterbium-176", abundance: "12.76%", stable: true },
    ],
  },
  {
    name: "Lutetium",
    symbol: "Lu",
    atomicNumber: 71,
    protons: 71,
    neutrons: 99,
    electrons: 71,
    color: 0x6a00ff,
    electronColor: 0x94ff00,
    xpos: 17,
    ypos: 8,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is classified as a Halogen (Highly Reactive).",
    melting: 1663,
    boiling: 3402,
    density: 9.84,
    yearDiscovered: 1907,
    uses: "Catalysts, phosphors, dating rocks",
    isotopes: [
      { mass: 175, neutrons: 104, name: "Lutetium-175", abundance: "97.41%", stable: true },
      { mass: 176, neutrons: 105, name: "Lutetium-176", abundance: "2.59%", stable: false },
    ],
  },
  {
    name: "Hafnium",
    symbol: "Hf",
    atomicNumber: 72,
    protons: 72,
    neutrons: 100,
    electrons: 72,
    color: 0xffb400,
    electronColor: 0x004aff,
    xpos: 4,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Hafnium is a chemical element with symbol Hf and atomic number 72. It is classified as a Moderate.",
    melting: 2233,
    boiling: 4603,
    density: 13.31,
    yearDiscovered: 1923,
    uses: "Nuclear reactors, microprocessors, plasma cutting",
    isotopes: [
      { mass: 174, neutrons: 102, name: "Hafnium-174", abundance: "0.16%", stable: true },
      { mass: 176, neutrons: 104, name: "Hafnium-176", abundance: "5.26%", stable: true },
      { mass: 177, neutrons: 105, name: "Hafnium-177", abundance: "18.60%", stable: true },
      { mass: 178, neutrons: 106, name: "Hafnium-178", abundance: "27.28%", stable: true },
      { mass: 179, neutrons: 107, name: "Hafnium-179", abundance: "13.62%", stable: true },
      { mass: 180, neutrons: 108, name: "Hafnium-180", abundance: "35.08%", stable: true },
    ],
  },
  {
    name: "Tantalum",
    symbol: "Ta",
    atomicNumber: 73,
    protons: 73,
    neutrons: 102,
    electrons: 73,
    color: 0x00ffff,
    electronColor: 0xff0000,
    xpos: 5,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Tantalum is a chemical element with symbol Ta and atomic number 73. It is classified as a Moderate.",
    melting: 3017,
    boiling: 5458,
    density: 16.654,
    yearDiscovered: 1802,
    uses: "Capacitors, surgical implants, jet engines",
    isotopes: [
      { mass: 180, neutrons: 107, name: "Tantalum-180m", abundance: "0.012%", stable: false },
      { mass: 181, neutrons: 108, name: "Tantalum-181", abundance: "99.988%", stable: true },
    ],
  },
  {
    name: "Tungsten",
    symbol: "W",
    atomicNumber: 74,
    protons: 74,
    neutrons: 103,
    electrons: 74,
    color: 0xff00b4,
    electronColor: 0x00ff4a,
    xpos: 6,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Tungsten is a chemical element with symbol W and atomic number 74. It is classified as a Moderate.",
    melting: 3422,
    boiling: 5555,
    density: 19.25,
    yearDiscovered: 1783,
    uses: "Light bulb filaments, cutting tools, armor",
    isotopes: [
      { mass: 180, neutrons: 106, name: "Tungsten-180", abundance: "0.12%", stable: true },
      { mass: 182, neutrons: 108, name: "Tungsten-182", abundance: "26.50%", stable: true },
      { mass: 183, neutrons: 109, name: "Tungsten-183", abundance: "14.31%", stable: true },
      { mass: 184, neutrons: 110, name: "Tungsten-184", abundance: "30.64%", stable: true },
      { mass: 186, neutrons: 112, name: "Tungsten-186", abundance: "28.43%", stable: true },
    ],
  },
  {
    name: "Rhenium",
    symbol: "Re",
    atomicNumber: 75,
    protons: 75,
    neutrons: 105,
    electrons: 75,
    color: 0x6aff00,
    electronColor: 0x9400ff,
    xpos: 7,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Rhenium is a chemical element with symbol Re and atomic number 75. It is classified as a Moderate.",
    melting: 3186,
    boiling: 5596,
    density: 21.02,
    yearDiscovered: 1925,
    uses: "Jet engines, catalysts, thermocouples",
    isotopes: [
      { mass: 185, neutrons: 110, name: "Rhenium-185", abundance: "37.40%", stable: true },
      { mass: 187, neutrons: 112, name: "Rhenium-187", abundance: "62.60%", stable: false },
    ],
  },
  {
    name: "Osmium",
    symbol: "Os",
    atomicNumber: 76,
    protons: 76,
    neutrons: 106,
    electrons: 76,
    color: 0x001fff,
    electronColor: 0xffdf00,
    xpos: 8,
    ypos: 6,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Osmium is a chemical element with symbol Os and atomic number 76. It is classified as a Noble Metal (Unreactive).",
    melting: 3033,
    boiling: 5012,
    density: 22.59,
    yearDiscovered: 1803,
    uses: "Fountain pen tips, electrical contacts, catalysts",
    isotopes: [
      { mass: 184, neutrons: 108, name: "Osmium-184", abundance: "0.02%", stable: true },
      { mass: 186, neutrons: 110, name: "Osmium-186", abundance: "1.59%", stable: true },
      { mass: 187, neutrons: 111, name: "Osmium-187", abundance: "1.96%", stable: true },
      { mass: 188, neutrons: 112, name: "Osmium-188", abundance: "13.24%", stable: true },
      { mass: 189, neutrons: 113, name: "Osmium-189", abundance: "16.15%", stable: true },
      { mass: 190, neutrons: 114, name: "Osmium-190", abundance: "26.26%", stable: true },
      { mass: 192, neutrons: 116, name: "Osmium-192", abundance: "40.78%", stable: true },
    ],
  },
  {
    name: "Iridium",
    symbol: "Ir",
    atomicNumber: 77,
    protons: 77,
    neutrons: 107,
    electrons: 77,
    color: 0xff2a00,
    electronColor: 0x00d4ff,
    xpos: 9,
    ypos: 6,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Iridium is a chemical element with symbol Ir and atomic number 77. It is classified as a Noble Metal (Unreactive).",
    melting: 2446,
    boiling: 4428,
    density: 22.56,
    yearDiscovered: 1803,
    uses: "Spark plugs, crucibles, electrical contacts",
    isotopes: [
      { mass: 191, neutrons: 114, name: "Iridium-191", abundance: "37.3%", stable: true },
      { mass: 193, neutrons: 116, name: "Iridium-193", abundance: "62.7%", stable: true },
    ],
  },
  {
    name: "Platinum",
    symbol: "Pt",
    atomicNumber: 78,
    protons: 78,
    neutrons: 109,
    electrons: 78,
    color: 0x00ff74,
    electronColor: 0xff008a,
    xpos: 10,
    ypos: 6,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Platinum is a chemical element with symbol Pt and atomic number 78. It is classified as a Noble Metal (Unreactive).",
    melting: 1768.3,
    boiling: 3825,
    density: 21.46,
    yearDiscovered: 1735,
    uses: "Catalytic converters, jewelry, laboratory equipment",
    isotopes: [
      { mass: 190, neutrons: 112, name: "Platinum-190", abundance: "0.014%", stable: false },
      { mass: 192, neutrons: 114, name: "Platinum-192", abundance: "0.782%", stable: true },
      { mass: 194, neutrons: 116, name: "Platinum-194", abundance: "32.967%", stable: true },
      { mass: 195, neutrons: 117, name: "Platinum-195", abundance: "33.832%", stable: true },
      { mass: 196, neutrons: 118, name: "Platinum-196", abundance: "25.242%", stable: true },
      { mass: 198, neutrons: 120, name: "Platinum-198", abundance: "7.163%", stable: true },
    ],
  },
  {
    name: "Gold",
    symbol: "Au",
    atomicNumber: 79,
    protons: 79,
    neutrons: 110,
    electrons: 79,
    color: 0xbf00ff,
    electronColor: 0x3fff00,
    xpos: 11,
    ypos: 6,
    reactivity: "Noble Metal (Unreactive)",
    isReactive: false,
    description: "Gold is a chemical element with symbol Au and atomic number 79. It is classified as a Noble Metal (Unreactive).",
    melting: 1064.18,
    boiling: 2856,
    density: 19.282,
    yearDiscovered: -6000,
    uses: "Jewelry, electronics, currency, dentistry",
    isotopes: [
      { mass: 197, neutrons: 118, name: "Gold-197", abundance: "100%", stable: true },
    ],
  },
  {
    name: "Mercury",
    symbol: "Hg",
    atomicNumber: 80,
    protons: 80,
    neutrons: 112,
    electrons: 80,
    color: 0xf4ff00,
    electronColor: 0x0a00ff,
    xpos: 12,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Mercury is a chemical element with symbol Hg and atomic number 80. It is classified as a Moderate.",
    melting: -38.83,
    boiling: 356.73,
    density: 13.5336,
    yearDiscovered: -1500,
    uses: "Thermometers, fluorescent lamps, dental amalgams",
    isotopes: [
      { mass: 196, neutrons: 116, name: "Mercury-196", abundance: "0.15%", stable: true },
      { mass: 198, neutrons: 118, name: "Mercury-198", abundance: "9.97%", stable: true },
      { mass: 199, neutrons: 119, name: "Mercury-199", abundance: "16.87%", stable: true },
      { mass: 200, neutrons: 120, name: "Mercury-200", abundance: "23.10%", stable: true },
      { mass: 201, neutrons: 121, name: "Mercury-201", abundance: "13.18%", stable: true },
      { mass: 202, neutrons: 122, name: "Mercury-202", abundance: "29.86%", stable: true },
      { mass: 204, neutrons: 124, name: "Mercury-204", abundance: "6.87%", stable: true },
    ],
  },
  {
    name: "Thallium",
    symbol: "Tl",
    atomicNumber: 81,
    protons: 81,
    neutrons: 121,
    electrons: 81,
    color: 0x00a9ff,
    electronColor: 0xff5400,
    xpos: 13,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Thallium is a chemical element with symbol Tl and atomic number 81. It is classified as a Moderate.",
    melting: 304,
    boiling: 1473,
    density: 11.85,
    yearDiscovered: 1861,
    uses: "Electronics, optics, medical imaging",
    isotopes: [
      { mass: 203, neutrons: 122, name: "Thallium-203", abundance: "29.52%", stable: true },
      { mass: 205, neutrons: 124, name: "Thallium-205", abundance: "70.48%", stable: true },
    ],
  },
  {
    name: "Lead",
    symbol: "Pb",
    atomicNumber: 82,
    protons: 82,
    neutrons: 123,
    electrons: 82,
    color: 0xff005f,
    electronColor: 0x00ff9f,
    xpos: 14,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Lead is a chemical element with symbol Pb and atomic number 82. It is classified as a Moderate.",
    melting: 327.46,
    boiling: 1749,
    density: 11.342,
    yearDiscovered: -7000,
    uses: "Batteries, radiation shielding, ammunition",
    isotopes: [
      { mass: 204, neutrons: 122, name: "Lead-204", abundance: "1.4%", stable: true },
      { mass: 206, neutrons: 124, name: "Lead-206", abundance: "24.1%", stable: true },
      { mass: 207, neutrons: 125, name: "Lead-207", abundance: "22.1%", stable: true },
      { mass: 208, neutrons: 126, name: "Lead-208", abundance: "52.4%", stable: true },
    ],
  },
  {
    name: "Bismuth",
    symbol: "Bi",
    atomicNumber: 83,
    protons: 83,
    neutrons: 124,
    electrons: 83,
    color: 0x15ff00,
    electronColor: 0xe900ff,
    xpos: 15,
    ypos: 6,
    reactivity: "Moderate",
    isReactive: false,
    description: "Bismuth is a chemical element with symbol Bi and atomic number 83. It is classified as a Moderate.",
    melting: 271.3,
    boiling: 1564,
    density: 9.807,
    yearDiscovered: 1753,
    uses: "Cosmetics, pharmaceuticals, fire detectors",
    isotopes: [
      { mass: 209, neutrons: 126, name: "Bismuth-209", abundance: "100%", stable: false },
    ],
  },
  {
    name: "Polonium",
    symbol: "Po",
    atomicNumber: 84,
    protons: 84,
    neutrons: 126,
    electrons: 84,
    color: 0x3500ff,
    electronColor: 0xc9ff00,
    xpos: 16,
    ypos: 6,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Polonium is a chemical element with symbol Po and atomic number 84. It is classified as a Chalcogen (Reactive).",
    melting: 254,
    boiling: 962,
    density: 9.32,
    yearDiscovered: 1898,
    uses: "Antistatic devices, nuclear batteries, research",
    isotopes: [
      { mass: 209, neutrons: 125, name: "Polonium-209", abundance: "trace", stable: false },
      { mass: 210, neutrons: 126, name: "Polonium-210", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Astatine",
    symbol: "At",
    atomicNumber: 85,
    protons: 85,
    neutrons: 127,
    electrons: 85,
    color: 0xff7f00,
    electronColor: 0x007fff,
    xpos: 17,
    ypos: 6,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Astatine is a chemical element with symbol At and atomic number 85. It is classified as a Halogen (Highly Reactive).",
    melting: 302,
    boiling: 337,
    density: 7,
    yearDiscovered: 1940,
    uses: "Cancer treatment research, radioactive tracers",
    isotopes: [
      { mass: 210, neutrons: 125, name: "Astatine-210", abundance: "trace", stable: false },
      { mass: 211, neutrons: 126, name: "Astatine-211", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Radon",
    symbol: "Rn",
    atomicNumber: 86,
    protons: 86,
    neutrons: 129,
    electrons: 86,
    color: 0x00ffc9,
    electronColor: 0xff0035,
    xpos: 18,
    ypos: 6,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Radon is a chemical element with symbol Rn and atomic number 86. It is classified as a Noble Gas (Inert).",
    melting: -71,
    boiling: -61.7,
    density: 0.00973,
    yearDiscovered: 1900,
    uses: "Cancer treatment, earthquake prediction, research",
    isotopes: [
      { mass: 222, neutrons: 136, name: "Radon-222", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Francium",
    symbol: "Fr",
    atomicNumber: 87,
    protons: 87,
    neutrons: 130,
    electrons: 87,
    color: 0xff00e9,
    electronColor: 0x00ff15,
    xpos: 1,
    ypos: 7,
    reactivity: "Alkali Metal (Highly Reactive)",
    isReactive: true,
    description: "Francium is a chemical element with symbol Fr and atomic number 87. It is classified as a Alkali Metal (Highly Reactive).",
    melting: 27,
    boiling: 677,
    density: 1.87,
    yearDiscovered: 1939,
    uses: "Scientific research, atomic structure studies",
    isotopes: [
      { mass: 223, neutrons: 136, name: "Francium-223", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Radium",
    symbol: "Ra",
    atomicNumber: 88,
    protons: 88,
    neutrons: 132,
    electrons: 88,
    color: 0x9fff00,
    electronColor: 0x5f00ff,
    xpos: 2,
    ypos: 7,
    reactivity: "Alkaline Earth Metal (Reactive)",
    isReactive: true,
    description: "Radium is a chemical element with symbol Ra and atomic number 88. It is classified as a Alkaline Earth Metal (Reactive).",
    melting: 696,
    boiling: 1737,
    density: 5,
    yearDiscovered: 1898,
    uses: "Cancer treatment, luminous paint, neutron sources",
    isotopes: [
      { mass: 226, neutrons: 138, name: "Radium-226", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Actinium",
    symbol: "Ac",
    atomicNumber: 89,
    protons: 89,
    neutrons: 133,
    electrons: 89,
    color: 0x0054ff,
    electronColor: 0xffaa00,
    xpos: 3,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Actinium is a chemical element with symbol Ac and atomic number 89. It is classified as a Radioactive/Reactive.",
    melting: 1051,
    boiling: 3198,
    density: 10.07,
    yearDiscovered: 1899,
    uses: "Neutron sources, cancer treatment research",
    isotopes: [
      { mass: 227, neutrons: 138, name: "Actinium-227", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Thorium",
    symbol: "Th",
    atomicNumber: 90,
    protons: 90,
    neutrons: 135,
    electrons: 90,
    color: 0xff000a,
    electronColor: 0x00fff4,
    xpos: 4,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Thorium is a chemical element with symbol Th and atomic number 90. It is classified as a Radioactive/Reactive.",
    melting: 1750,
    boiling: 4820,
    density: 11.72,
    yearDiscovered: 1828,
    uses: "Nuclear fuel, gas mantles, welding electrodes",
    isotopes: [
      { mass: 232, neutrons: 142, name: "Thorium-232", abundance: "100%", stable: false },
    ],
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    atomicNumber: 91,
    protons: 91,
    neutrons: 136,
    electrons: 91,
    color: 0x00ff3f,
    electronColor: 0xff00bf,
    xpos: 5,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is classified as a Radioactive/Reactive.",
    melting: 1572,
    boiling: 4000,
    density: 15.37,
    yearDiscovered: 1913,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 231, neutrons: 140, name: "Protactinium-231", abundance: "100%", stable: false },
    ],
  },
  {
    name: "Uranium",
    symbol: "U",
    atomicNumber: 92,
    protons: 92,
    neutrons: 138,
    electrons: 92,
    color: 0x8a00ff,
    electronColor: 0x74ff00,
    xpos: 6,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Uranium is a chemical element with symbol U and atomic number 92. It is classified as a Radioactive/Reactive.",
    melting: 1135,
    boiling: 4131,
    density: 18.95,
    yearDiscovered: 1789,
    uses: "Nuclear fuel, weapons, depleted uranium armor",
    isotopes: [
      { mass: 234, neutrons: 142, name: "Uranium-234", abundance: "0.005%", stable: false },
      { mass: 235, neutrons: 143, name: "Uranium-235", abundance: "0.720%", stable: false },
      { mass: 238, neutrons: 146, name: "Uranium-238", abundance: "99.274%", stable: false },
    ],
  },
  {
    name: "Neptunium",
    symbol: "Np",
    atomicNumber: 93,
    protons: 93,
    neutrons: 139,
    electrons: 93,
    color: 0xffd400,
    electronColor: 0x002aff,
    xpos: 7,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Neptunium is a chemical element with symbol Np and atomic number 93. It is classified as a Radioactive/Reactive.",
    melting: 644,
    boiling: 4000,
    density: 20.45,
    yearDiscovered: 1940,
    uses: "Neutron detection, plutonium production, research",
    isotopes: [
      { mass: 237, neutrons: 144, name: "Neptunium-237", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Plutonium",
    symbol: "Pu",
    atomicNumber: 94,
    protons: 94,
    neutrons: 141,
    electrons: 94,
    color: 0x00dfff,
    electronColor: 0xff1f00,
    xpos: 8,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Plutonium is a chemical element with symbol Pu and atomic number 94. It is classified as a Radioactive/Reactive.",
    melting: 640,
    boiling: 3228,
    density: 19.84,
    yearDiscovered: 1940,
    uses: "Nuclear weapons, spacecraft power, research",
    isotopes: [
      { mass: 238, neutrons: 144, name: "Plutonium-238", abundance: "trace", stable: false },
      { mass: 239, neutrons: 145, name: "Plutonium-239", abundance: "trace", stable: false },
      { mass: 240, neutrons: 146, name: "Plutonium-240", abundance: "trace", stable: false },
      { mass: 241, neutrons: 147, name: "Plutonium-241", abundance: "trace", stable: false },
      { mass: 242, neutrons: 148, name: "Plutonium-242", abundance: "trace", stable: false },
      { mass: 244, neutrons: 150, name: "Plutonium-244", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Americium",
    symbol: "Am",
    atomicNumber: 95,
    protons: 95,
    neutrons: 142,
    electrons: 95,
    color: 0xff0094,
    electronColor: 0x00ff6a,
    xpos: 9,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Americium is a chemical element with symbol Am and atomic number 95. It is classified as a Radioactive/Reactive.",
    melting: 1176,
    boiling: 2011,
    density: 13.69,
    yearDiscovered: 1944,
    uses: "Smoke detectors, neutron sources, research",
    isotopes: [
      { mass: 241, neutrons: 146, name: "Americium-241", abundance: "trace", stable: false },
      { mass: 243, neutrons: 148, name: "Americium-243", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Curium",
    symbol: "Cm",
    atomicNumber: 96,
    protons: 96,
    neutrons: 144,
    electrons: 96,
    color: 0x4aff00,
    electronColor: 0xb400ff,
    xpos: 10,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Curium is a chemical element with symbol Cm and atomic number 96. It is classified as a Radioactive/Reactive.",
    melting: 1345,
    boiling: 3110,
    density: 13.51,
    yearDiscovered: 1944,
    uses: "Spacecraft power, alpha particle sources, research",
    isotopes: [
      { mass: 243, neutrons: 147, name: "Curium-243", abundance: "trace", stable: false },
      { mass: 244, neutrons: 148, name: "Curium-244", abundance: "trace", stable: false },
      { mass: 245, neutrons: 149, name: "Curium-245", abundance: "trace", stable: false },
      { mass: 246, neutrons: 150, name: "Curium-246", abundance: "trace", stable: false },
      { mass: 247, neutrons: 151, name: "Curium-247", abundance: "trace", stable: false },
      { mass: 248, neutrons: 152, name: "Curium-248", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    atomicNumber: 97,
    protons: 97,
    neutrons: 145,
    electrons: 97,
    color: 0x0000ff,
    electronColor: 0xffff00,
    xpos: 11,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Berkelium is a chemical element with symbol Bk and atomic number 97. It is classified as a Radioactive/Reactive.",
    melting: 1050,
    boiling: 2900,
    density: 14.79,
    yearDiscovered: 1949,
    uses: "Scientific research, element synthesis",
    isotopes: [
      { mass: 247, neutrons: 150, name: "Berkelium-247", abundance: "trace", stable: false },
      { mass: 249, neutrons: 152, name: "Berkelium-249", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Californium",
    symbol: "Cf",
    atomicNumber: 98,
    protons: 98,
    neutrons: 147,
    electrons: 98,
    color: 0xff4a00,
    electronColor: 0x00b4ff,
    xpos: 12,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Californium is a chemical element with symbol Cf and atomic number 98. It is classified as a Radioactive/Reactive.",
    melting: 900,
    boiling: 1470,
    density: 15.1,
    yearDiscovered: 1950,
    uses: "Neutron sources, cancer treatment, metal detectors",
    isotopes: [
      { mass: 249, neutrons: 151, name: "Californium-249", abundance: "trace", stable: false },
      { mass: 250, neutrons: 152, name: "Californium-250", abundance: "trace", stable: false },
      { mass: 251, neutrons: 153, name: "Californium-251", abundance: "trace", stable: false },
      { mass: 252, neutrons: 154, name: "Californium-252", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Einsteinium",
    symbol: "Es",
    atomicNumber: 99,
    protons: 99,
    neutrons: 148,
    electrons: 99,
    color: 0x00ff94,
    electronColor: 0xff006a,
    xpos: 13,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Einsteinium is a chemical element with symbol Es and atomic number 99. It is classified as a Radioactive/Reactive.",
    melting: 860,
    boiling: 1130,
    density: 8.84,
    yearDiscovered: 1952,
    uses: "Scientific research, element synthesis",
    isotopes: [
      { mass: 252, neutrons: 153, name: "Einsteinium-252", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Fermium",
    symbol: "Fm",
    atomicNumber: 100,
    protons: 100,
    neutrons: 150,
    electrons: 100,
    color: 0xdf00ff,
    electronColor: 0x1fff00,
    xpos: 14,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Fermium is a chemical element with symbol Fm and atomic number 100. It is classified as a Radioactive/Reactive.",
    melting: 1527,
    boiling: null,
    density: null,
    yearDiscovered: 1952,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 257, neutrons: 157, name: "Fermium-257", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Mendelevium",
    symbol: "Md",
    atomicNumber: 101,
    protons: 101,
    neutrons: 151,
    electrons: 101,
    color: 0xd4ff00,
    electronColor: 0x2a00ff,
    xpos: 15,
    ypos: 9,
    reactivity: "Radioactive/Reactive",
    isReactive: true,
    description: "Mendelevium is a chemical element with symbol Md and atomic number 101. It is classified as a Radioactive/Reactive.",
    melting: 827,
    boiling: null,
    density: null,
    yearDiscovered: 1955,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 258, neutrons: 157, name: "Mendelevium-258", abundance: "trace", stable: false },
      { mass: 260, neutrons: 159, name: "Mendelevium-260", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Nobelium",
    symbol: "No",
    atomicNumber: 102,
    protons: 102,
    neutrons: 153,
    electrons: 102,
    color: 0x008aff,
    electronColor: 0xff7400,
    xpos: 16,
    ypos: 9,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Nobelium is a chemical element with symbol No and atomic number 102. It is classified as a Chalcogen (Reactive).",
    melting: 827,
    boiling: null,
    density: null,
    yearDiscovered: 1958,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 259, neutrons: 157, name: "Nobelium-259", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Lawrencium",
    symbol: "Lr",
    atomicNumber: 103,
    protons: 103,
    neutrons: 154,
    electrons: 103,
    color: 0xff003f,
    electronColor: 0x00ffbf,
    xpos: 17,
    ypos: 9,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Lawrencium is a chemical element with symbol Lr and atomic number 103. It is classified as a Halogen (Highly Reactive).",
    melting: 1627,
    boiling: null,
    density: null,
    yearDiscovered: 1961,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 262, neutrons: 159, name: "Lawrencium-262", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Rutherfordium",
    symbol: "Rf",
    atomicNumber: 104,
    protons: 104,
    neutrons: 156,
    electrons: 104,
    color: 0x00ff0a,
    electronColor: 0xff00f4,
    xpos: 4,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Rutherfordium is a chemical element with symbol Rf and atomic number 104. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1964,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 267, neutrons: 163, name: "Rutherfordium-267", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Dubnium",
    symbol: "Db",
    atomicNumber: 105,
    protons: 105,
    neutrons: 157,
    electrons: 105,
    color: 0x5400ff,
    electronColor: 0xaaff00,
    xpos: 5,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Dubnium is a chemical element with symbol Db and atomic number 105. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1968,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 268, neutrons: 163, name: "Dubnium-268", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Seaborgium",
    symbol: "Sg",
    atomicNumber: 106,
    protons: 106,
    neutrons: 159,
    electrons: 106,
    color: 0xff9f00,
    electronColor: 0x005fff,
    xpos: 6,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Seaborgium is a chemical element with symbol Sg and atomic number 106. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1974,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 271, neutrons: 165, name: "Seaborgium-271", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Bohrium",
    symbol: "Bh",
    atomicNumber: 107,
    protons: 107,
    neutrons: 160,
    electrons: 107,
    color: 0x00ffe9,
    electronColor: 0xff0015,
    xpos: 7,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Bohrium is a chemical element with symbol Bh and atomic number 107. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1981,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 270, neutrons: 163, name: "Bohrium-270", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Hassium",
    symbol: "Hs",
    atomicNumber: 108,
    protons: 108,
    neutrons: 162,
    electrons: 108,
    color: 0xff00c9,
    electronColor: 0x00ff35,
    xpos: 8,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Hassium is a chemical element with symbol Hs and atomic number 108. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1984,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 270, neutrons: 162, name: "Hassium-270", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Meitnerium",
    symbol: "Mt",
    atomicNumber: 109,
    protons: 109,
    neutrons: 163,
    electrons: 109,
    color: 0x7fff00,
    electronColor: 0x7f00ff,
    xpos: 9,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1982,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 278, neutrons: 169, name: "Meitnerium-278", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Darmstadtium",
    symbol: "Ds",
    atomicNumber: 110,
    protons: 110,
    neutrons: 165,
    electrons: 110,
    color: 0x0035ff,
    electronColor: 0xffc900,
    xpos: 10,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1994,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 281, neutrons: 171, name: "Darmstadtium-281", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Roentgenium",
    symbol: "Rg",
    atomicNumber: 111,
    protons: 111,
    neutrons: 166,
    electrons: 111,
    color: 0xff1500,
    electronColor: 0x00e9ff,
    xpos: 11,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1994,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 282, neutrons: 171, name: "Roentgenium-282", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Copernicium",
    symbol: "Cn",
    atomicNumber: 112,
    protons: 112,
    neutrons: 168,
    electrons: 112,
    color: 0x00ff5f,
    electronColor: 0xff009f,
    xpos: 12,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1996,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 285, neutrons: 173, name: "Copernicium-285", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Nihonium",
    symbol: "Nh",
    atomicNumber: 113,
    protons: 113,
    neutrons: 169,
    electrons: 113,
    color: 0xaa00ff,
    electronColor: 0x54ff00,
    xpos: 13,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Nihonium is a chemical element with symbol Nh and atomic number 113. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 2004,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 286, neutrons: 173, name: "Nihonium-286", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Flerovium",
    symbol: "Fl",
    atomicNumber: 114,
    protons: 114,
    neutrons: 171,
    electrons: 114,
    color: 0xfff400,
    electronColor: 0x000aff,
    xpos: 14,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Flerovium is a chemical element with symbol Fl and atomic number 114. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 1998,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 289, neutrons: 175, name: "Flerovium-289", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Moscovium",
    symbol: "Mc",
    atomicNumber: 115,
    protons: 115,
    neutrons: 172,
    electrons: 115,
    color: 0x00bfff,
    electronColor: 0xff3f00,
    xpos: 15,
    ypos: 7,
    reactivity: "Moderate",
    isReactive: false,
    description: "Moscovium is a chemical element with symbol Mc and atomic number 115. It is classified as a Moderate.",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 2003,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 290, neutrons: 175, name: "Moscovium-290", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Livermorium",
    symbol: "Lv",
    atomicNumber: 116,
    protons: 116,
    neutrons: 174,
    electrons: 116,
    color: 0xff0074,
    electronColor: 0x00ff8a,
    xpos: 16,
    ypos: 7,
    reactivity: "Chalcogen (Reactive)",
    isReactive: true,
    description: "Livermorium is a chemical element with symbol Lv and atomic number 116. It is classified as a Chalcogen (Reactive).",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 2000,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 293, neutrons: 177, name: "Livermorium-293", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Tennessine",
    symbol: "Ts",
    atomicNumber: 117,
    protons: 117,
    neutrons: 175,
    electrons: 117,
    color: 0x2aff00,
    electronColor: 0xd400ff,
    xpos: 17,
    ypos: 7,
    reactivity: "Halogen (Highly Reactive)",
    isReactive: true,
    description: "Tennessine is a chemical element with symbol Ts and atomic number 117. It is classified as a Halogen (Highly Reactive).",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 2010,
    uses: "Scientific research, nuclear physics",
    isotopes: [
      { mass: 294, neutrons: 177, name: "Tennessine-294", abundance: "trace", stable: false },
    ],
  },
  {
    name: "Oganesson",
    symbol: "Og",
    atomicNumber: 118,
    protons: 118,
    neutrons: 177,
    electrons: 118,
    color: 0x1f00ff,
    electronColor: 0xdfff00,
    xpos: 18,
    ypos: 7,
    reactivity: "Noble Gas (Inert)",
    isReactive: false,
    description: "Oganesson is a chemical element with symbol Og and atomic number 118. It is classified as a Noble Gas (Inert).",
    melting: null,
    boiling: null,
    density: null,
    yearDiscovered: 2002,
    uses: "Scientific research, nuclear studies",
    isotopes: [
      { mass: 294, neutrons: 176, name: "Oganesson-294", abundance: "trace", stable: false },
    ],
  },
];
