export const atoms = [
  {
    name: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    protons: 1,
    neutrons: 1,
    electrons: 1,
    color: 0xff0000,
    electronColor: 0x00ffff,
    xpos: 1,
    ypos: 1
  },
  {
    name: "Helium",
    symbol: "He",
    atomicNumber: 2,
    protons: 2,
    neutrons: 2,
    electrons: 2,
    color: 0x00ff4a,
    electronColor: 0xff00b4,
    xpos: 18,
    ypos: 1
  },
  {
    name: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    protons: 3,
    neutrons: 3,
    electrons: 3,
    color: 0x9400ff,
    electronColor: 0x6aff00,
    xpos: 1,
    ypos: 2
  },
  {
    name: "Beryllium",
    symbol: "Be",
    atomicNumber: 4,
    protons: 4,
    neutrons: 4,
    electrons: 4,
    color: 0xffdf00,
    electronColor: 0x001fff,
    xpos: 2,
    ypos: 2
  },
  {
    name: "Boron",
    symbol: "B",
    atomicNumber: 5,
    protons: 5,
    neutrons: 5,
    electrons: 5,
    color: 0x00d4ff,
    electronColor: 0xff2a00,
    xpos: 13,
    ypos: 2
  },
  {
    name: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    protons: 6,
    neutrons: 6,
    electrons: 6,
    color: 0xff008a,
    electronColor: 0x00ff74,
    xpos: 14,
    ypos: 2
  },
  {
    name: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    protons: 7,
    neutrons: 7,
    electrons: 7,
    color: 0x3fff00,
    electronColor: 0xbf00ff,
    xpos: 15,
    ypos: 2
  },
  {
    name: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    protons: 8,
    neutrons: 8,
    electrons: 8,
    color: 0x0a00ff,
    electronColor: 0xf4ff00,
    xpos: 16,
    ypos: 2
  },
  {
    name: "Fluorine",
    symbol: "F",
    atomicNumber: 9,
    protons: 9,
    neutrons: 9,
    electrons: 9,
    color: 0xff5400,
    electronColor: 0x00a9ff,
    xpos: 17,
    ypos: 2
  },
  {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    protons: 10,
    neutrons: 10,
    electrons: 10,
    color: 0x00ff9f,
    electronColor: 0xff005f,
    xpos: 18,
    ypos: 2
  },
  {
    name: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    protons: 11,
    neutrons: 11,
    electrons: 11,
    color: 0xe900ff,
    electronColor: 0x15ff00,
    xpos: 1,
    ypos: 3
  },
  {
    name: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    protons: 12,
    neutrons: 12,
    electrons: 12,
    color: 0xc9ff00,
    electronColor: 0x3500ff,
    xpos: 2,
    ypos: 3
  },
  {
    name: "Aluminum",
    symbol: "Al",
    atomicNumber: 13,
    protons: 13,
    neutrons: 13,
    electrons: 13,
    color: 0x007fff,
    electronColor: 0xff7f00,
    xpos: 13,
    ypos: 3
  },
  {
    name: "Silicon",
    symbol: "Si",
    atomicNumber: 14,
    protons: 14,
    neutrons: 14,
    electrons: 14,
    color: 0xff0035,
    electronColor: 0x00ffc9,
    xpos: 14,
    ypos: 3
  },
  {
    name: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    protons: 15,
    neutrons: 15,
    electrons: 15,
    color: 0x00ff15,
    electronColor: 0xff00e9,
    xpos: 15,
    ypos: 3
  },
  {
    name: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    protons: 16,
    neutrons: 16,
    electrons: 16,
    color: 0x5f00ff,
    electronColor: 0x9fff00,
    xpos: 16,
    ypos: 3
  },
  {
    name: "Chlorine",
    symbol: "Cl",
    atomicNumber: 17,
    protons: 17,
    neutrons: 17,
    electrons: 17,
    color: 0xffaa00,
    electronColor: 0x0054ff,
    xpos: 17,
    ypos: 3
  },
  {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    protons: 18,
    neutrons: 18,
    electrons: 18,
    color: 0x00fff4,
    electronColor: 0xff000a,
    xpos: 18,
    ypos: 3
  },
  {
    name: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    protons: 19,
    neutrons: 19,
    electrons: 19,
    color: 0xff00bf,
    electronColor: 0x00ff3f,
    xpos: 1,
    ypos: 4
  },
  {
    name: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    protons: 20,
    neutrons: 20,
    electrons: 20,
    color: 0x74ff00,
    electronColor: 0x8a00ff,
    xpos: 2,
    ypos: 4
  },
  {
    name: "Scandium",
    symbol: "Sc",
    atomicNumber: 21,
    protons: 21,
    neutrons: 25,
    electrons: 21,
    color: 0x002aff,
    electronColor: 0xffd400,
    xpos: 3,
    ypos: 4
  },
  {
    name: "Titanium",
    symbol: "Ti",
    atomicNumber: 22,
    protons: 22,
    neutrons: 26,
    electrons: 22,
    color: 0xff1f00,
    electronColor: 0x00dfff,
    xpos: 4,
    ypos: 4
  },
  {
    name: "Vanadium",
    symbol: "V",
    atomicNumber: 23,
    protons: 23,
    neutrons: 27,
    electrons: 23,
    color: 0x00ff6a,
    electronColor: 0xff0094,
    xpos: 5,
    ypos: 4
  },
  {
    name: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    protons: 24,
    neutrons: 28,
    electrons: 24,
    color: 0xb400ff,
    electronColor: 0x4aff00,
    xpos: 6,
    ypos: 4
  },
  {
    name: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    protons: 25,
    neutrons: 30,
    electrons: 25,
    color: 0xffff00,
    electronColor: 0x0000ff,
    xpos: 7,
    ypos: 4
  },
  {
    name: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    protons: 26,
    neutrons: 31,
    electrons: 26,
    color: 0x00b4ff,
    electronColor: 0xff4a00,
    xpos: 8,
    ypos: 4
  },
  {
    name: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    protons: 27,
    neutrons: 32,
    electrons: 27,
    color: 0xff006a,
    electronColor: 0x00ff94,
    xpos: 9,
    ypos: 4
  },
  {
    name: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    protons: 28,
    neutrons: 33,
    electrons: 28,
    color: 0x1fff00,
    electronColor: 0xdf00ff,
    xpos: 10,
    ypos: 4
  },
  {
    name: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    protons: 29,
    neutrons: 34,
    electrons: 29,
    color: 0x2a00ff,
    electronColor: 0xd4ff00,
    xpos: 11,
    ypos: 4
  },
  {
    name: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    protons: 30,
    neutrons: 36,
    electrons: 30,
    color: 0xff7400,
    electronColor: 0x008aff,
    xpos: 12,
    ypos: 4
  },
  {
    name: "Gallium",
    symbol: "Ga",
    atomicNumber: 31,
    protons: 31,
    neutrons: 37,
    electrons: 31,
    color: 0x00ffbf,
    electronColor: 0xff003f,
    xpos: 13,
    ypos: 4
  },
  {
    name: "Germanium",
    symbol: "Ge",
    atomicNumber: 32,
    protons: 32,
    neutrons: 38,
    electrons: 32,
    color: 0xff00f4,
    electronColor: 0x00ff0a,
    xpos: 14,
    ypos: 4
  },
  {
    name: "Arsenic",
    symbol: "As",
    atomicNumber: 33,
    protons: 33,
    neutrons: 39,
    electrons: 33,
    color: 0xaaff00,
    electronColor: 0x5400ff,
    xpos: 15,
    ypos: 4
  },
  {
    name: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    protons: 34,
    neutrons: 40,
    electrons: 34,
    color: 0x005fff,
    electronColor: 0xff9f00,
    xpos: 16,
    ypos: 4
  },
  {
    name: "Bromine",
    symbol: "Br",
    atomicNumber: 35,
    protons: 35,
    neutrons: 42,
    electrons: 35,
    color: 0xff0015,
    electronColor: 0x00ffe9,
    xpos: 17,
    ypos: 4
  },
  {
    name: "Krypton",
    symbol: "Kr",
    atomicNumber: 36,
    protons: 36,
    neutrons: 43,
    electrons: 36,
    color: 0x00ff35,
    electronColor: 0xff00c9,
    xpos: 18,
    ypos: 4
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    atomicNumber: 37,
    protons: 37,
    neutrons: 44,
    electrons: 37,
    color: 0x7f00ff,
    electronColor: 0x7fff00,
    xpos: 1,
    ypos: 5
  },
  {
    name: "Strontium",
    symbol: "Sr",
    atomicNumber: 38,
    protons: 38,
    neutrons: 45,
    electrons: 38,
    color: 0xffc900,
    electronColor: 0x0035ff,
    xpos: 2,
    ypos: 5
  },
  {
    name: "Yttrium",
    symbol: "Y",
    atomicNumber: 39,
    protons: 39,
    neutrons: 46,
    electrons: 39,
    color: 0x00e9ff,
    electronColor: 0xff1500,
    xpos: 3,
    ypos: 5
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    atomicNumber: 40,
    protons: 40,
    neutrons: 48,
    electrons: 40,
    color: 0xff009f,
    electronColor: 0x00ff5f,
    xpos: 4,
    ypos: 5
  },
  {
    name: "Niobium",
    symbol: "Nb",
    atomicNumber: 41,
    protons: 41,
    neutrons: 49,
    electrons: 41,
    color: 0x54ff00,
    electronColor: 0xaa00ff,
    xpos: 5,
    ypos: 5
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    protons: 42,
    neutrons: 50,
    electrons: 42,
    color: 0x000aff,
    electronColor: 0xfff400,
    xpos: 6,
    ypos: 5
  },
  {
    name: "Technetium",
    symbol: "Tc",
    atomicNumber: 43,
    protons: 43,
    neutrons: 51,
    electrons: 43,
    color: 0xff3f00,
    electronColor: 0x00bfff,
    xpos: 7,
    ypos: 5
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    atomicNumber: 44,
    protons: 44,
    neutrons: 52,
    electrons: 44,
    color: 0x00ff8a,
    electronColor: 0xff0074,
    xpos: 8,
    ypos: 5
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    atomicNumber: 45,
    protons: 45,
    neutrons: 54,
    electrons: 45,
    color: 0xd400ff,
    electronColor: 0x2aff00,
    xpos: 9,
    ypos: 5
  },
  {
    name: "Palladium",
    symbol: "Pd",
    atomicNumber: 46,
    protons: 46,
    neutrons: 55,
    electrons: 46,
    color: 0xdfff00,
    electronColor: 0x1f00ff,
    xpos: 10,
    ypos: 5
  },
  {
    name: "Silver",
    symbol: "Ag",
    atomicNumber: 47,
    protons: 47,
    neutrons: 56,
    electrons: 47,
    color: 0x0094ff,
    electronColor: 0xff6a00,
    xpos: 11,
    ypos: 5
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    atomicNumber: 48,
    protons: 48,
    neutrons: 57,
    electrons: 48,
    color: 0xff004a,
    electronColor: 0x00ffb4,
    xpos: 12,
    ypos: 5
  },
  {
    name: "Indium",
    symbol: "In",
    atomicNumber: 49,
    protons: 49,
    neutrons: 58,
    electrons: 49,
    color: 0x00ff00,
    electronColor: 0xff00ff,
    xpos: 13,
    ypos: 5
  },
  {
    name: "Tin",
    symbol: "Sn",
    atomicNumber: 50,
    protons: 50,
    neutrons: 60,
    electrons: 50,
    color: 0x4a00ff,
    electronColor: 0xb4ff00,
    xpos: 14,
    ypos: 5
  },
  {
    name: "Antimony",
    symbol: "Sb",
    atomicNumber: 51,
    protons: 51,
    neutrons: 71,
    electrons: 51,
    color: 0xff9400,
    electronColor: 0x006aff,
    xpos: 15,
    ypos: 5
  },
  {
    name: "Tellurium",
    symbol: "Te",
    atomicNumber: 52,
    protons: 52,
    neutrons: 72,
    electrons: 52,
    color: 0x00ffdf,
    electronColor: 0xff001f,
    xpos: 16,
    ypos: 5
  },
  {
    name: "Iodine",
    symbol: "I",
    atomicNumber: 53,
    protons: 53,
    neutrons: 74,
    electrons: 53,
    color: 0xff00d4,
    electronColor: 0x00ff2a,
    xpos: 17,
    ypos: 5
  },
  {
    name: "Xenon",
    symbol: "Xe",
    atomicNumber: 54,
    protons: 54,
    neutrons: 75,
    electrons: 54,
    color: 0x8aff00,
    electronColor: 0x7400ff,
    xpos: 18,
    ypos: 5
  },
  {
    name: "Cesium",
    symbol: "Cs",
    atomicNumber: 55,
    protons: 55,
    neutrons: 77,
    electrons: 55,
    color: 0x003fff,
    electronColor: 0xffbf00,
    xpos: 1,
    ypos: 6
  },
  {
    name: "Barium",
    symbol: "Ba",
    atomicNumber: 56,
    protons: 56,
    neutrons: 78,
    electrons: 56,
    color: 0xff0a00,
    electronColor: 0x00f4ff,
    xpos: 2,
    ypos: 6
  },
  {
    name: "Lanthanum",
    symbol: "La",
    atomicNumber: 57,
    protons: 57,
    neutrons: 79,
    electrons: 57,
    color: 0x00ff55,
    electronColor: 0xff00aa,
    xpos: 3,
    ypos: 8
  },
  {
    name: "Cerium",
    symbol: "Ce",
    atomicNumber: 58,
    protons: 58,
    neutrons: 81,
    electrons: 58,
    color: 0x9f00ff,
    electronColor: 0x5fff00,
    xpos: 4,
    ypos: 8
  },
  {
    name: "Praseodymium",
    symbol: "Pr",
    atomicNumber: 59,
    protons: 59,
    neutrons: 82,
    electrons: 59,
    color: 0xffe900,
    electronColor: 0x0015ff,
    xpos: 5,
    ypos: 8
  },
  {
    name: "Neodymium",
    symbol: "Nd",
    atomicNumber: 60,
    protons: 60,
    neutrons: 84,
    electrons: 60,
    color: 0x00c9ff,
    electronColor: 0xff3500,
    xpos: 6,
    ypos: 8
  },
  {
    name: "Promethium",
    symbol: "Pm",
    atomicNumber: 61,
    protons: 61,
    neutrons: 85,
    electrons: 61,
    color: 0xff007f,
    electronColor: 0x00ff7f,
    xpos: 7,
    ypos: 8
  },
  {
    name: "Samarium",
    symbol: "Sm",
    atomicNumber: 62,
    protons: 62,
    neutrons: 86,
    electrons: 62,
    color: 0x35ff00,
    electronColor: 0xc900ff,
    xpos: 8,
    ypos: 8
  },
  {
    name: "Europium",
    symbol: "Eu",
    atomicNumber: 63,
    protons: 63,
    neutrons: 88,
    electrons: 63,
    color: 0x1500ff,
    electronColor: 0xe9ff00,
    xpos: 9,
    ypos: 8
  },
  {
    name: "Gadolinium",
    symbol: "Gd",
    atomicNumber: 64,
    protons: 64,
    neutrons: 89,
    electrons: 64,
    color: 0xff5f00,
    electronColor: 0x009fff,
    xpos: 10,
    ypos: 8
  },
  {
    name: "Terbium",
    symbol: "Tb",
    atomicNumber: 65,
    protons: 65,
    neutrons: 91,
    electrons: 65,
    color: 0x00ffa9,
    electronColor: 0xff0055,
    xpos: 11,
    ypos: 8
  },
  {
    name: "Dysprosium",
    symbol: "Dy",
    atomicNumber: 66,
    protons: 66,
    neutrons: 92,
    electrons: 66,
    color: 0xf400ff,
    electronColor: 0x0aff00,
    xpos: 12,
    ypos: 8
  },
  {
    name: "Holmium",
    symbol: "Ho",
    atomicNumber: 67,
    protons: 67,
    neutrons: 93,
    electrons: 67,
    color: 0xbfff00,
    electronColor: 0x3f00ff,
    xpos: 13,
    ypos: 8
  },
  {
    name: "Erbium",
    symbol: "Er",
    atomicNumber: 68,
    protons: 68,
    neutrons: 95,
    electrons: 68,
    color: 0x0074ff,
    electronColor: 0xff8a00,
    xpos: 14,
    ypos: 8
  },
  {
    name: "Thulium",
    symbol: "Tm",
    atomicNumber: 69,
    protons: 69,
    neutrons: 96,
    electrons: 69,
    color: 0xff002a,
    electronColor: 0x00ffd4,
    xpos: 15,
    ypos: 8
  },
  {
    name: "Ytterbium",
    symbol: "Yb",
    atomicNumber: 70,
    protons: 70,
    neutrons: 98,
    electrons: 70,
    color: 0x00ff1f,
    electronColor: 0xff00df,
    xpos: 16,
    ypos: 8
  },
  {
    name: "Lutetium",
    symbol: "Lu",
    atomicNumber: 71,
    protons: 71,
    neutrons: 99,
    electrons: 71,
    color: 0x6a00ff,
    electronColor: 0x94ff00,
    xpos: 17,
    ypos: 8
  },
  {
    name: "Hafnium",
    symbol: "Hf",
    atomicNumber: 72,
    protons: 72,
    neutrons: 100,
    electrons: 72,
    color: 0xffb400,
    electronColor: 0x004aff,
    xpos: 4,
    ypos: 6
  },
  {
    name: "Tantalum",
    symbol: "Ta",
    atomicNumber: 73,
    protons: 73,
    neutrons: 102,
    electrons: 73,
    color: 0x00ffff,
    electronColor: 0xff0000,
    xpos: 5,
    ypos: 6
  },
  {
    name: "Tungsten",
    symbol: "W",
    atomicNumber: 74,
    protons: 74,
    neutrons: 103,
    electrons: 74,
    color: 0xff00b4,
    electronColor: 0x00ff4a,
    xpos: 6,
    ypos: 6
  },
  {
    name: "Rhenium",
    symbol: "Re",
    atomicNumber: 75,
    protons: 75,
    neutrons: 105,
    electrons: 75,
    color: 0x6aff00,
    electronColor: 0x9400ff,
    xpos: 7,
    ypos: 6
  },
  {
    name: "Osmium",
    symbol: "Os",
    atomicNumber: 76,
    protons: 76,
    neutrons: 106,
    electrons: 76,
    color: 0x001fff,
    electronColor: 0xffdf00,
    xpos: 8,
    ypos: 6
  },
  {
    name: "Iridium",
    symbol: "Ir",
    atomicNumber: 77,
    protons: 77,
    neutrons: 107,
    electrons: 77,
    color: 0xff2a00,
    electronColor: 0x00d4ff,
    xpos: 9,
    ypos: 6
  },
  {
    name: "Platinum",
    symbol: "Pt",
    atomicNumber: 78,
    protons: 78,
    neutrons: 109,
    electrons: 78,
    color: 0x00ff74,
    electronColor: 0xff008a,
    xpos: 10,
    ypos: 6
  },
  {
    name: "Gold",
    symbol: "Au",
    atomicNumber: 79,
    protons: 79,
    neutrons: 110,
    electrons: 79,
    color: 0xbf00ff,
    electronColor: 0x3fff00,
    xpos: 11,
    ypos: 6
  },
  {
    name: "Mercury",
    symbol: "Hg",
    atomicNumber: 80,
    protons: 80,
    neutrons: 112,
    electrons: 80,
    color: 0xf4ff00,
    electronColor: 0x0a00ff,
    xpos: 12,
    ypos: 6
  },
  {
    name: "Thallium",
    symbol: "Tl",
    atomicNumber: 81,
    protons: 81,
    neutrons: 121,
    electrons: 81,
    color: 0x00a9ff,
    electronColor: 0xff5400,
    xpos: 13,
    ypos: 6
  },
  {
    name: "Lead",
    symbol: "Pb",
    atomicNumber: 82,
    protons: 82,
    neutrons: 123,
    electrons: 82,
    color: 0xff005f,
    electronColor: 0x00ff9f,
    xpos: 14,
    ypos: 6
  },
  {
    name: "Bismuth",
    symbol: "Bi",
    atomicNumber: 83,
    protons: 83,
    neutrons: 124,
    electrons: 83,
    color: 0x15ff00,
    electronColor: 0xe900ff,
    xpos: 15,
    ypos: 6
  },
  {
    name: "Polonium",
    symbol: "Po",
    atomicNumber: 84,
    protons: 84,
    neutrons: 126,
    electrons: 84,
    color: 0x3500ff,
    electronColor: 0xc9ff00,
    xpos: 16,
    ypos: 6
  },
  {
    name: "Astatine",
    symbol: "At",
    atomicNumber: 85,
    protons: 85,
    neutrons: 127,
    electrons: 85,
    color: 0xff7f00,
    electronColor: 0x007fff,
    xpos: 17,
    ypos: 6
  },
  {
    name: "Radon",
    symbol: "Rn",
    atomicNumber: 86,
    protons: 86,
    neutrons: 129,
    electrons: 86,
    color: 0x00ffc9,
    electronColor: 0xff0035,
    xpos: 18,
    ypos: 6
  },
  {
    name: "Francium",
    symbol: "Fr",
    atomicNumber: 87,
    protons: 87,
    neutrons: 130,
    electrons: 87,
    color: 0xff00e9,
    electronColor: 0x00ff15,
    xpos: 1,
    ypos: 7
  },
  {
    name: "Radium",
    symbol: "Ra",
    atomicNumber: 88,
    protons: 88,
    neutrons: 132,
    electrons: 88,
    color: 0x9fff00,
    electronColor: 0x5f00ff,
    xpos: 2,
    ypos: 7
  },
  {
    name: "Actinium",
    symbol: "Ac",
    atomicNumber: 89,
    protons: 89,
    neutrons: 133,
    electrons: 89,
    color: 0x0054ff,
    electronColor: 0xffaa00,
    xpos: 3,
    ypos: 9
  },
  {
    name: "Thorium",
    symbol: "Th",
    atomicNumber: 90,
    protons: 90,
    neutrons: 135,
    electrons: 90,
    color: 0xff000a,
    electronColor: 0x00fff4,
    xpos: 4,
    ypos: 9
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    atomicNumber: 91,
    protons: 91,
    neutrons: 136,
    electrons: 91,
    color: 0x00ff3f,
    electronColor: 0xff00bf,
    xpos: 5,
    ypos: 9
  },
  {
    name: "Uranium",
    symbol: "U",
    atomicNumber: 92,
    protons: 92,
    neutrons: 138,
    electrons: 92,
    color: 0x8a00ff,
    electronColor: 0x74ff00,
    xpos: 6,
    ypos: 9
  },
  {
    name: "Neptunium",
    symbol: "Np",
    atomicNumber: 93,
    protons: 93,
    neutrons: 139,
    electrons: 93,
    color: 0xffd400,
    electronColor: 0x002aff,
    xpos: 7,
    ypos: 9
  },
  {
    name: "Plutonium",
    symbol: "Pu",
    atomicNumber: 94,
    protons: 94,
    neutrons: 141,
    electrons: 94,
    color: 0x00dfff,
    electronColor: 0xff1f00,
    xpos: 8,
    ypos: 9
  },
  {
    name: "Americium",
    symbol: "Am",
    atomicNumber: 95,
    protons: 95,
    neutrons: 142,
    electrons: 95,
    color: 0xff0094,
    electronColor: 0x00ff6a,
    xpos: 9,
    ypos: 9
  },
  {
    name: "Curium",
    symbol: "Cm",
    atomicNumber: 96,
    protons: 96,
    neutrons: 144,
    electrons: 96,
    color: 0x4aff00,
    electronColor: 0xb400ff,
    xpos: 10,
    ypos: 9
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    atomicNumber: 97,
    protons: 97,
    neutrons: 145,
    electrons: 97,
    color: 0x0000ff,
    electronColor: 0xffff00,
    xpos: 11,
    ypos: 9
  },
  {
    name: "Californium",
    symbol: "Cf",
    atomicNumber: 98,
    protons: 98,
    neutrons: 147,
    electrons: 98,
    color: 0xff4a00,
    electronColor: 0x00b4ff,
    xpos: 12,
    ypos: 9
  },
  {
    name: "Einsteinium",
    symbol: "Es",
    atomicNumber: 99,
    protons: 99,
    neutrons: 148,
    electrons: 99,
    color: 0x00ff94,
    electronColor: 0xff006a,
    xpos: 13,
    ypos: 9
  },
  {
    name: "Fermium",
    symbol: "Fm",
    atomicNumber: 100,
    protons: 100,
    neutrons: 150,
    electrons: 100,
    color: 0xdf00ff,
    electronColor: 0x1fff00,
    xpos: 14,
    ypos: 9
  },
  {
    name: "Mendelevium",
    symbol: "Md",
    atomicNumber: 101,
    protons: 101,
    neutrons: 151,
    electrons: 101,
    color: 0xd4ff00,
    electronColor: 0x2a00ff,
    xpos: 15,
    ypos: 9
  },
  {
    name: "Nobelium",
    symbol: "No",
    atomicNumber: 102,
    protons: 102,
    neutrons: 153,
    electrons: 102,
    color: 0x008aff,
    electronColor: 0xff7400,
    xpos: 16,
    ypos: 9
  },
  {
    name: "Lawrencium",
    symbol: "Lr",
    atomicNumber: 103,
    protons: 103,
    neutrons: 154,
    electrons: 103,
    color: 0xff003f,
    electronColor: 0x00ffbf,
    xpos: 17,
    ypos: 9
  },
  {
    name: "Rutherfordium",
    symbol: "Rf",
    atomicNumber: 104,
    protons: 104,
    neutrons: 156,
    electrons: 104,
    color: 0x00ff0a,
    electronColor: 0xff00f4,
    xpos: 4,
    ypos: 7
  },
  {
    name: "Dubnium",
    symbol: "Db",
    atomicNumber: 105,
    protons: 105,
    neutrons: 157,
    electrons: 105,
    color: 0x5400ff,
    electronColor: 0xaaff00,
    xpos: 5,
    ypos: 7
  },
  {
    name: "Seaborgium",
    symbol: "Sg",
    atomicNumber: 106,
    protons: 106,
    neutrons: 159,
    electrons: 106,
    color: 0xff9f00,
    electronColor: 0x005fff,
    xpos: 6,
    ypos: 7
  },
  {
    name: "Bohrium",
    symbol: "Bh",
    atomicNumber: 107,
    protons: 107,
    neutrons: 160,
    electrons: 107,
    color: 0x00ffe9,
    electronColor: 0xff0015,
    xpos: 7,
    ypos: 7
  },
  {
    name: "Hassium",
    symbol: "Hs",
    atomicNumber: 108,
    protons: 108,
    neutrons: 162,
    electrons: 108,
    color: 0xff00c9,
    electronColor: 0x00ff35,
    xpos: 8,
    ypos: 7
  },
  {
    name: "Meitnerium",
    symbol: "Mt",
    atomicNumber: 109,
    protons: 109,
    neutrons: 163,
    electrons: 109,
    color: 0x7fff00,
    electronColor: 0x7f00ff,
    xpos: 9,
    ypos: 7
  },
  {
    name: "Darmstadtium",
    symbol: "Ds",
    atomicNumber: 110,
    protons: 110,
    neutrons: 165,
    electrons: 110,
    color: 0x0035ff,
    electronColor: 0xffc900,
    xpos: 10,
    ypos: 7
  },
  {
    name: "Roentgenium",
    symbol: "Rg",
    atomicNumber: 111,
    protons: 111,
    neutrons: 166,
    electrons: 111,
    color: 0xff1500,
    electronColor: 0x00e9ff,
    xpos: 11,
    ypos: 7
  },
  {
    name: "Copernicium",
    symbol: "Cn",
    atomicNumber: 112,
    protons: 112,
    neutrons: 168,
    electrons: 112,
    color: 0x00ff5f,
    electronColor: 0xff009f,
    xpos: 12,
    ypos: 7
  },
  {
    name: "Nihonium",
    symbol: "Nh",
    atomicNumber: 113,
    protons: 113,
    neutrons: 169,
    electrons: 113,
    color: 0xaa00ff,
    electronColor: 0x54ff00,
    xpos: 13,
    ypos: 7
  },
  {
    name: "Flerovium",
    symbol: "Fl",
    atomicNumber: 114,
    protons: 114,
    neutrons: 171,
    electrons: 114,
    color: 0xfff400,
    electronColor: 0x000aff,
    xpos: 14,
    ypos: 7
  },
  {
    name: "Moscovium",
    symbol: "Mc",
    atomicNumber: 115,
    protons: 115,
    neutrons: 172,
    electrons: 115,
    color: 0x00bfff,
    electronColor: 0xff3f00,
    xpos: 15,
    ypos: 7
  },
  {
    name: "Livermorium",
    symbol: "Lv",
    atomicNumber: 116,
    protons: 116,
    neutrons: 174,
    electrons: 116,
    color: 0xff0074,
    electronColor: 0x00ff8a,
    xpos: 16,
    ypos: 7
  },
  {
    name: "Tennessine",
    symbol: "Ts",
    atomicNumber: 117,
    protons: 117,
    neutrons: 175,
    electrons: 117,
    color: 0x2aff00,
    electronColor: 0xd400ff,
    xpos: 17,
    ypos: 7
  },
  {
    name: "Oganesson",
    symbol: "Og",
    atomicNumber: 118,
    protons: 118,
    neutrons: 177,
    electrons: 118,
    color: 0x1f00ff,
    electronColor: 0xdfff00,
    xpos: 18,
    ypos: 7
  },
];
